create table public.lt_yasmin_studio_sessions_internal (id uuid primary key, revision bigint not null default 0, data jsonb not null, created_at timestamptz not null default now());
create table public.lt_yasmin_studio_accounts_internal (username text primary key, session_id uuid not null references public.lt_yasmin_studio_sessions_internal(id), password_salt text not null, password_hash text not null, failed_attempts integer not null default 0, locked_until timestamptz);
create table public.lt_yasmin_studio_tokens_internal (token_hash text primary key, session_id uuid not null references public.lt_yasmin_studio_sessions_internal(id) on delete cascade, expires_at timestamptz not null, created_at timestamptz not null default now());
create index lt_yasmin_studio_tokens_session_idx on public.lt_yasmin_studio_tokens_internal(session_id);
create table public.lt_yasmin_studio_push_config_internal (id integer primary key check (id=1), vapid_public text not null, vapid_private text not null);
create table public.lt_yasmin_studio_push_subscriptions_internal (endpoint text primary key, session_id uuid not null references public.lt_yasmin_studio_sessions_internal(id) on delete cascade, subscription jsonb not null, updated_at timestamptz not null default now());
create index lt_yasmin_studio_push_session_idx on public.lt_yasmin_studio_push_subscriptions_internal(session_id);
create table public.lt_yasmin_studio_push_deliveries_internal (session_id uuid not null references public.lt_yasmin_studio_sessions_internal(id) on delete cascade, event_key text not null, status text not null, sent integer not null default 0, attempted integer not null default 0, created_at timestamptz not null default now(), primary key(session_id,event_key));
alter table public.lt_yasmin_studio_sessions_internal enable row level security;
alter table public.lt_yasmin_studio_accounts_internal enable row level security;
alter table public.lt_yasmin_studio_tokens_internal enable row level security;
alter table public.lt_yasmin_studio_push_config_internal enable row level security;
alter table public.lt_yasmin_studio_push_subscriptions_internal enable row level security;
alter table public.lt_yasmin_studio_push_deliveries_internal enable row level security;
revoke all on public.lt_yasmin_studio_sessions_internal, public.lt_yasmin_studio_accounts_internal, public.lt_yasmin_studio_tokens_internal, public.lt_yasmin_studio_push_config_internal, public.lt_yasmin_studio_push_subscriptions_internal, public.lt_yasmin_studio_push_deliveries_internal from public, anon, authenticated;
grant select,insert,update,delete on public.lt_yasmin_studio_sessions_internal, public.lt_yasmin_studio_accounts_internal, public.lt_yasmin_studio_tokens_internal, public.lt_yasmin_studio_push_config_internal, public.lt_yasmin_studio_push_subscriptions_internal, public.lt_yasmin_studio_push_deliveries_internal to service_role;
