const $=id=>document.getElementById(id),key='lt_pf_teste_admin';
let adminKey=new URLSearchParams(location.hash.slice(1)).get('chave');
try{if(adminKey)sessionStorage.setItem(key,adminKey);else adminKey=sessionStorage.getItem(key)||localStorage.getItem(key)}catch{}
history.replaceState(null,'',location.pathname);
async function call(action,fields={}){
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);
 try{const r=await fetch('https://wwietlvweqsxfpejhhis.supabase.co/functions/v1/lt-meu-financeiro-teste-cadastro',{method:'POST',headers:{apikey:'sb_publishable_dArUUh2qpDqbzvjxXAEbNQ_hT6Y0y5y','Content-Type':'application/json'},body:JSON.stringify({action,adminKey,...fields}),signal:controller.signal});const data=await r.json();if(!r.ok)throw Error(data.message);return data}finally{clearTimeout(timer)}
}
async function load(){
 $('reload').disabled=true;$('status').textContent='Buscando cadastros…';
 try{const data=await call('adminList');try{localStorage.setItem(key,adminKey)}catch{}$('controlAccess').hidden=true;$('registrations').replaceChildren();$('status').textContent=data.users.length+' de '+data.limit+' acessos cadastrados.';
  for(const user of data.users){const card=document.createElement('section');card.className='card';const name=document.createElement('h2');name.textContent=user.name;const login=document.createElement('p');login.textContent='Login: '+user.username;const status=document.createElement('p');status.textContent=user.active?'✓ Autorizado':'Aguardando sua autorização';card.append(name,login,status);const phone=document.createElement('p');phone.textContent='Telefone: '+(user.phone||'Não cadastrado');card.append(phone);if(user.phone){const whatsapp=document.createElement('a');whatsapp.className='secondary';whatsapp.href='https://wa.me/'+user.phone;whatsapp.target='_blank';whatsapp.rel='noopener noreferrer';whatsapp.textContent='Chamar no WhatsApp para confirmar';card.append(whatsapp)}const editPhone=document.createElement('button');editPhone.type='button';editPhone.className='text-button';editPhone.textContent='Cadastrar / alterar telefone';editPhone.onclick=async()=>{const phone=prompt('Telefone de '+user.name+' com DDD:',user.phone||'');if(phone===null)return;try{await call('setPhone',{userId:user.id,phone});await load()}catch(e){$('status').textContent=e.message}};card.append(editPhone);
   if(!user.active){const button=document.createElement('button');button.type='button';button.textContent='Autorizar acesso';button.onclick=async()=>{if(!confirm('Autorizar o acesso de '+user.name+' ('+user.username+')?'))return;button.disabled=true;try{await call('approve',{userId:user.id});await load()}catch(e){$('status').textContent=e.message;button.disabled=false}};card.append(button)}
   const reset=document.createElement('button');reset.type='button';reset.className='secondary';reset.textContent=user.resetRequested?'Autorizar reset de senha':'Redefinir senha';reset.onclick=()=>openReset(user);if(user.resetRequested){const notice=document.createElement('p');notice.textContent='⚠ Cliente solicitou recuperação de senha.';card.append(notice)}card.append(reset);$('registrations').append(card);
  }
 }catch(e){$('status').textContent=e.name==='AbortError'?'Sem resposta. Tente novamente.':e.message}
 finally{$('reload').disabled=false}
}
$('reload').onclick=load;
if(adminKey)load();else{$('status').textContent='Entre com seu código de controle ou abra seu link exclusivo.';$('controlAccess').hidden=false;$('reload').disabled=true}

$('controlAccess').onsubmit=e=>{e.preventDefault();adminKey=$('controlKey').value.trim();load();};

function openReset(user){
 let dialog=$('resetDialog');
 if(!dialog){dialog=document.createElement('dialog');dialog.id='resetDialog';dialog.innerHTML='<form id="resetForm"><h2 id="resetTitle"></h2><p class="muted">Você autoriza a troca e informa a nova senha ao cliente. Os dados financeiros serão preservados e ele deverá entrar novamente nos aparelhos.</p><label for="resetNew">Nova senha</label><input id="resetNew" type="password" minlength="8" maxlength="100" autocomplete="new-password" required><button id="resetShow" type="button" class="text-button">Mostrar senha</button><label for="resetConfirm">Confirme a nova senha</label><input id="resetConfirm" type="password" minlength="8" maxlength="100" autocomplete="new-password" required><p id="resetError" class="error" role="alert"></p><label class="permission-option"><input id="resetIdentityConfirmed" type="checkbox" required><span>Confirmei a identidade deste cliente por contato.</span></label><button id="resetSave" type="submit">Autorizar e redefinir senha</button><button id="resetCancel" type="button" class="secondary">Cancelar</button></form>';document.body.append(dialog);$('resetCancel').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{$('resetForm').reset();});$('resetShow').onclick=()=>{const show=$('resetNew').type==='password';$('resetNew').type=$('resetConfirm').type=show?'text':'password';$('resetShow').textContent=show?'Ocultar senha':'Mostrar senha';};}
 $('resetForm').reset();$('resetNew').type=$('resetConfirm').type='password';$('resetShow').textContent='Mostrar senha';$('resetTitle').textContent='Redefinir senha de '+user.name+' ('+user.username+')';$('resetError').textContent='';$('resetSave').disabled=false;
 $('resetForm').onsubmit=async e=>{e.preventDefault();if($('resetNew').value!==$('resetConfirm').value){$('resetError').textContent='As senhas precisam ser iguais.';return}if(!confirm('Autorizar a redefinição da senha de '+user.username+'?'))return;$('resetSave').disabled=true;try{await call('resetPassword',{userId:user.id,password:$('resetNew').value,confirmedIdentity:$('resetIdentityConfirmed').checked});dialog.close();await load();$('status').textContent='Senha redefinida. Informe a nova senha ao cliente. Ele precisa entrar novamente.'}catch(e){$('resetError').textContent=e.message}finally{$('resetSave').disabled=false}};dialog.showModal();
}
