import {permissionLabels,readPermissions} from './permissions.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createUserManager({request,currentUser,render,toast,document}){
 const $=id=>document.getElementById(id);let users=[],loading=false,error='',editing=null,saving=false;
 const owner=()=>currentUser()?.isOwner===true;
 async function load(){if(!owner()||loading)return;const actor=currentUser().id;loading=true;error='';render();try{const result=await request({action:'usersList'});if(owner()&&currentUser().id===actor)users=result.users;}catch(e){error=e.message;}finally{loading=false;render();}}
 function view(){return '<div class="page-head"><div><h2>Usuários e acessos</h2><p class="muted">Cada pessoa entra com seu próprio login.</p></div><button id="addUser">+ Usuário</button></div><div class="card"><p>Você é o administrador. Escolha o que cada pessoa pode consultar ou alterar neste financeiro.</p><p class="muted">A consulta libera todos os saldos, gastos e contas deste espaço. As conversas continuam individuais. Desativar um acesso preserva os lançamentos já registrados.</p></div>'+(error?'<div class="card"><p class="error" role="alert">'+esc(error)+'</p><button id="retryUsers" class="secondary">Tentar novamente</button></div>':'')+(loading?'<p role="status">Carregando usuários…</p>':users.map(u=>'<div class="card user-access-card"><div class="entry-header"><div><h3>'+esc(u.name)+'</h3><p class="muted">'+esc(u.username)+'</p></div><span class="badge '+(!u.active?'pending':'')+'">'+(u.isOwner?'Administrador':u.active?'Ativo':'Desativado')+'</span></div><p class="muted">'+(u.isOwner?'Acesso completo e protegido.':Object.keys(permissionLabels).filter(k=>u.permissions?.[k]).map(k=>({view:'Consulta',entries:'Lançamentos',invoices:'Faturas',accounts:'Contas',cards:'Cartões',budgets:'Orçamentos'}[k])).join(' · ')||'Sem acesso ao financeiro')+'</p>'+(!u.isOwner?'<button class="secondary" data-edit-user="'+u.id+'">Configurar acesso</button>':'')+'</div>').join(''));}
 function open(u=null){if(!owner())return;editing=u?{...u}:{id:crypto.randomUUID(),permissions:readPermissions()};$('userEditorTitle').textContent=u?'Configurar acesso':'Adicionar usuário';$('managedName').value=u?.name||'';$('managedLogin').value=u?.username||'';$('managedLogin').disabled=!!u;$('managedPassword').value='';$('managedPassword').required=!u;$('managedPassword').placeholder=u?'Deixe vazio para manter a senha':'Senha com pelo menos 8 caracteres';$('managedActive').checked=u?.active!==false;$('managedActiveLabel').hidden=!u;$('managedPermissions').innerHTML=Object.entries(permissionLabels).map(([key,label])=>'<label class="permission-option"><input type="checkbox" id="permission_'+key+'" '+(editing.permissions?.[key]?'checked':'')+'><span>'+esc(label)+'</span></label>').join('');$('permission_view').onchange=syncChecks;syncChecks();$('managedUserError').textContent='';$('userEditor').showModal();}
 function syncChecks(){const view=$('permission_view').checked;for(const key of Object.keys(permissionLabels)){if(key==='view')continue;const input=$('permission_'+key);input.disabled=!view;if(!view)input.checked=false;}}
 function close(){if(saving)return;$('managedPassword').value='';editing=null;$('userEditor').close();}
 $('closeUserEditor').onclick=close;$('userEditor').addEventListener('cancel',e=>{if(saving)e.preventDefault();else close();});$('userEditor').addEventListener('close',()=>{if(!saving){editing=null;$('managedPassword').value='';}});
 $('managedUserForm').onsubmit=async e=>{e.preventDefault();if(!owner()||saving||!editing)return;saving=true;$('saveManagedUser').disabled=true;$('managedUserError').textContent='';try{const permissions=Object.fromEntries(Object.keys(permissionLabels).map(k=>[k,$('permission_'+k).checked]));await request({action:editing.username?'userUpdate':'userCreate',id:editing.id,version:editing.version,name:$('managedName').value,username:$('managedLogin').value,password:$('managedPassword').value,permissions,active:$('managedActive').checked});saving=false;close();toast('Usuário e permissões salvos.');await load();}catch(e){$('managedUserError').textContent=e.message;}finally{saving=false;$('saveManagedUser').disabled=false;}};
 return {view,load,reset(){users=[];editing=null;error='';$('managedPassword').value='';$('userEditor').close();},bind(){if($('addUser'))$('addUser').onclick=()=>open();if($('retryUsers'))$('retryUsers').onclick=load;document.querySelectorAll('[data-edit-user]').forEach(b=>b.onclick=()=>open(users.find(u=>u.id===b.dataset.editUser)));},get saving(){return saving}};
}
