import {test} from 'node:test';import assert from 'node:assert/strict';import {mutate} from '../ledger.js';import {budgetSpent,budgetReply} from '../budget.js';
const user={name:'Luciano'},stamp='2026-10-06T15:00:00Z',id='00000000-0000-4000-8000-000000000050',account='00000000-0000-4000-8000-000000000001';
const base={accounts:[{id:account,name:'Dinheiro',openingCents:50000}],entries:[],cards:[],invoices:[]};
const configure=s=>mutate(mutate(s,{action:'budgetSettings',enabled:true,version:s.budgetSettings?.version||0},user,stamp),{action:'budget',id,category:'Combustível',month:'2026-10',limitCents:10000},user,stamp);
const entry={kind:'expense',description:'Gasolina',category:'Transporte',cents:12000,accountId:account,date:'2026-10-06',status:'paid',scope:'casal'};
test('opcional, limite mensal, cálculo por combustível e aviso histórico preservam dados',()=>{assert.match(budgetReply('quanto ainda posso gastar de combustível',base,'2026-10-06'),/desativado/);let s=configure(base);assert.match(budgetReply('quanto posso gastar em combustível',s,'2026-10-06'),/100,00/);s=mutate(s,{action:'entry',id:'00000000-0000-4000-8000-000000000060',createOnly:true,entry},user,stamp);assert.equal(budgetSpent(s,s.budgets[0]),12000);assert.equal(s.budgetAlerts.length,1);assert.equal(s.budgetAlerts[0].excessCents,2000);assert.match(budgetReply('quanto ainda posso gastar de combustível',s,'2026-10-06'),/Passou do orçamento em R\$\s*20,00/);const before=JSON.stringify(s.entries);const e=s.budgetAlerts[0];s=mutate(s,{action:'budgetResponse',id:e.id,version:0,response:'note',note:'Viagem extra'},user,stamp);assert.equal(s.budgetAlerts[0].note,'Viagem extra');assert.equal(JSON.stringify(s.entries),before);s=mutate(s,{action:'budgetSettings',enabled:false,version:1},user,stamp);assert.equal(s.budgetAlerts[0].note,'Viagem extra');assert.equal(s.budgets[0].limitCents,10000);assert.equal(base.entries.length,0)});
test('sem justificativa é permitido e concorrência/financeiro alheio são rejeitados',()=>{let s=configure({...base,entries:[{...entry,id:'e'}]});const alert=s.budgetAlerts[0];s=mutate(s,{action:'budgetResponse',id:alert.id,version:0,response:'skip'},user,stamp);assert.equal(s.budgetAlerts[0].response,'skip');assert.throws(()=>mutate(s,{action:'budgetResponse',id:alert.id,version:0,response:'note',note:'Outra'},user,stamp),e=>e.status===409);assert.throws(()=>mutate(s,{action:'budgetResponse',id:'outro-financeiro',version:0,response:'skip'},user,stamp),e=>e.status===404);assert.throws(()=>mutate(s,{action:'budget',id,category:'Combustível',month:'2026-10',limitCents:20000,version:0},user,stamp),e=>e.status===409);assert.throws(()=>mutate(s,{action:'budgetSettings',enabled:false,version:0},user,stamp),e=>e.status===409);assert.throws(()=>mutate(s,{action:'budget',id:'00000000-0000-4000-8000-000000000051',category:'Combustível',month:'2026-10',limitCents:20000},user,stamp));});
test('crédito conta pela compra, pneus não são combustível, excluídos e outros meses não entram',()=>{const s=configure({...base,entries:[{...entry,cents:1000,cardId:'card',status:'pending',paidDate:null},{...entry,cents:2000,description:'Diesel',cardId:'card',paidDate:'2026-11-13'},{...entry,description:'Pneus',cents:99000},{...entry,description:'Gasolina',deleted:true},{...entry,date:'2026-09-01',paidDate:'2026-09-01'},{...entry,status:'pending',paidDate:null}]});assert.equal(budgetSpent(s,s.budgets[0]),3000);assert.equal(s.budgetAlerts?.length||0,0);assert.equal(budgetReply('gastei 30 em combustível',s,'2026-10-06'),null);assert.equal(budgetReply('quanto de limite tem no cartão',s,'2026-10-06'),null)});
test('editar limite guarda limite anterior e não remove justificativas ao registrar nova despesa',()=>{let s=configure({...base,entries:[{...entry,id:'e'}]});const event=s.budgetAlerts[0];s=mutate(s,{action:'budgetResponse',id:event.id,version:0,response:'note',note:'Gasolina aumentou'},user,stamp);s=mutate(s,{action:'budget',id,category:'Combustível',month:'2026-10',limitCents:15000,version:1},user,stamp);assert.equal(s.budgets[0].changes[0].limitCents,10000);assert.equal(s.budgetAlerts[0].note,'Gasolina aumentou');s=mutate(s,{action:'entry',id:'00000000-0000-4000-8000-000000000062',createOnly:true,entry:{...entry,cents:5000}},user,stamp);assert.equal(s.budgetAlerts.length,2);assert.equal(s.budgetAlerts[1].excessCents,2000);assert.equal(s.budgetAlerts[0].note,'Gasolina aumentou')});
