import {test} from 'node:test';
import assert from 'node:assert/strict';
import {cardSpendingReply,cardLimitReply} from '../../../clientes/financeiro-luciano-yasmin/card-query.js';
const cards=[{id:'a',name:'Sicredi',closingDay:29,dueDay:13,limitCents:100000},{id:'b',name:'Nubank',closingDay:20,dueDay:2,limitCents:200000}];
const item=(cardId,cents,more={})=>({kind:'expense',cardId,cents,date:'2026-10-06',invoiceId:cardId+'_2026-10',status:'pending',...more});
const data={cards,invoices:[],entries:[item('a',3000),item('a',1000,{deleted:true}),item('a',5000,{invoiceId:'a_2026-09',date:'2026-09-20',status:'paid'}),item('b',2000),item(null,99000,{invoiceId:null,status:'paid'}),item('a',1500,{invoiceId:'a_2026-11',date:'2026-10-30'})]};
test('pergunta exata soma compras pendentes por cartão sem misturar dinheiro e excluídos',()=>{const before=JSON.stringify(data),r=cardSpendingReply('quanto gastei no cartão de crédito',data,'2026-10-06');assert.match(r.text,/50,00/);assert.match(r.text,/Sicredi: R\$\s*30,00/);assert.match(r.text,/Nubank: R\$\s*20,00/);assert.match(r.text,/vencimento para 13\/11\/2026/);assert.match(r.text,/45,00/);assert.equal(JSON.stringify(data),before)});
test('nome do cartão, fatura, fechamento e períodos respeitam compras em vez do dia do pagamento',()=>{assert.doesNotMatch(cardSpendingReply('quanto gastei no cartão Sicredi',data,'2026-10-06').text,/Nubank/);assert.match(cardSpendingReply('qual o total da fatura Sicredi',data,'2026-10-06').text,/30,00/);assert.match(cardSpendingReply('quanto gastei no cartão Sicredi neste mês',data,'2026-10-06').text,/45,00/);assert.match(cardSpendingReply('quanto gastei no cartão Sicredi no mês passado',data,'2026-10-06').text,/50,00/);assert.match(cardSpendingReply('quanto gastei no cartão Sicredi hoje',data,'2026-10-06').text,/30,00/);assert.match(cardSpendingReply('quanto gastei no cartão Sicredi no total',data,'2026-10-06').text,/95,00/);assert.match(cardSpendingReply('quanto gastei no cartão Sicredi',data,'2026-10-30').text,/15,00/)});
test('consulta nunca vira lançamento e pergunta de limite conserva comportamento',()=>{assert.equal(cardSpendingReply('gastei 30,00 no cartão Sicredi',data,'2026-10-06'),null);assert.equal(cardSpendingReply('quanto gastei no mercado',data,'2026-10-06'),null);assert.equal(cardSpendingReply('quanto de limite tem no cartão Sicredi',data,'2026-10-06'),null);assert.match(cardLimitReply('quanto de limite tem no cartão Sicredi',data).text,/Limite disponível/);assert.match(cardSpendingReply('quanto gastei no cartão Bradesco',data,'2026-10-06').text,/Não encontrei/);assert.match(cardSpendingReply('quanto gastei no cartão de crédito',{cards:[],entries:[]},'2026-10-06').text,/não tem cartões/)});

test('consulta plural mostra limite de cada cartão sem pedir para escolher',()=>{const before=JSON.stringify(data);for(const text of ['QUANTO TENHO DE LIMITE NOS CARTÕES','quais os limites dos cartões','qual o limite de cada cartão']){const r=cardLimitReply(text,data,true);assert.equal(r.awaitingChoice,false);assert.match(r.text,/Sicredi:\nLimite disponível: R\$\s*955,00\.\nLimite total: R\$\s*1\.000,00\.\nUtilizado: R\$\s*45,00/);assert.match(r.text,/Nubank:\nLimite disponível: R\$\s*1\.980,00\.\nLimite total: R\$\s*2\.000,00\.\nUtilizado: R\$\s*20,00/);assert.doesNotMatch(r.text,/Qual cartão/);}assert.equal(JSON.stringify(data),before);const unknown={...data,cards:[...cards,{id:'c',name:'Cartão sem limite'}],entries:[...data.entries,item('c',500)]};assert.match(cardLimitReply('quanto tenho de limite nos cartões',unknown).text,/Cartão sem limite:\nLimite total e disponível: ainda não informados[\s\S]*Utilizado: R\$\s*5,00/);assert.doesNotMatch(cardLimitReply('quanto de limite tem no cartão Sicredi',data).text,/Nubank/)});

test('consulta de cartões detalha as compras da mesma fatura usada no total',()=>{const detailData={...data,entries:[item('a',2500,{description:'Recarga celular'}),item('b',5000,{description:'Gasolina'}),item('a',9900,{description:'Excluída',deleted:true}),item('a',7000,{description:'Outra fatura',invoiceId:'a_2026-09',date:'2026-09-10'})]};const r=cardSpendingReply('quanto eu gastei nos cartões',detailData,'2026-10-06').text;assert.match(r,/Sicredi: R\$\s*25,00/);assert.match(r,/• 06\/10\/2026 · Recarga celular · R\$\s*25,00/);assert.match(r,/Nubank: R\$\s*50,00/);assert.match(r,/• 06\/10\/2026 · Gasolina · R\$\s*50,00/);assert.match(r,/Total nos cartões consultados: R\$\s*75,00/);assert.doesNotMatch(r,/Excluída|Outra fatura/);assert.equal((r.match(/Recarga celular/g)||[]).length,1);assert.match(cardSpendingReply('quanto gastei no cartão Sicredi',{...detailData,entries:[]},'2026-10-06').text,/Nenhuma compra registrada nesta fatura/)});
