import {test} from 'node:test';import assert from 'node:assert/strict';import {mutate,summarize} from '../ledger.js';import {invoiceDates,purchaseCycle,invoiceId,invoiceTotal} from '../credit.js';
const cardId='00000000-0000-4000-8000-000000000010',accountId='00000000-0000-4000-8000-000000000001',id='00000000-0000-4000-8000-000000000020',u={name:'Luciano'},now='2026-10-06T15:00:00Z';
const card={id:cardId,name:'Sicredi',closingDay:29,dueDay:13,version:1};const empty={accounts:[{id:accountId,name:'Conta Sicredi',openingCents:100000,version:1}],entries:[],cards:[card],invoices:[]};const e={kind:'expense',cents:3000,description:'Recarga do celular',category:'Serviços',cardId,status:'pending',date:'2026-10-06',scope:'luciano'};
function purchase(state=empty){return mutate(state,{action:'entry',id,createOnly:true,entry:e},u,now)}
test('compra entra na fatura e só altera saldo quando paga',()=>{let s=purchase();let b=s.invoices[0];assert.equal(b.cycle,'2026-10');assert.equal(b.dueDate,'2026-11-13');assert.equal(invoiceTotal(s,b.id),3000);assert.equal(summarize(s,'2026-10').balance,100000);assert.equal(summarize(s,'2026-11').payable,3000);s=mutate(s,{action:'invoiceClose',id:b.id,version:b.version,confirmedCents:3000},u,now);b=s.invoices[0];s=mutate(s,{action:'invoicePay',id:b.id,version:b.version,confirmedCents:3000,accountId,paidDate:'2026-11-13'},u,now);assert.equal(summarize(s,'2026-11').balance,97000);assert.equal(summarize(s,'2026-11').expense,3000);assert.equal(summarize(s,'2026-11').payable,0);assert.throws(()=>mutate(s,{action:'invoicePay',id:b.id,version:b.version,confirmedCents:3000,accountId,paidDate:'2026-11-13'},u,now));assert.equal(mutate(s,{action:'entry',id,createOnly:true,entry:e},u,now).entries.length,1)});
test('diferença não ajusta o saldo e impede fechar até lançar compra faltante',()=>{let s=purchase(),b=s.invoices[0];s=mutate(s,{action:'invoiceCheck',id:b.id,version:b.version,bankCents:5000},u,now);b=s.invoices[0];assert.equal(b.bankCents-invoiceTotal(s,b.id),2000);assert.throws(()=>mutate(s,{action:'invoiceClose',id:b.id,version:b.version,confirmedCents:3000},u,now));s=mutate(s,{action:'entry',id:'00000000-0000-4000-8000-000000000021',createOnly:true,entry:{...e,cents:2000}},u,now);b=s.invoices[0];assert.equal(invoiceTotal(s,b.id),5000);assert.equal(summarize(s,'2026-10').balance,100000);assert.equal(mutate(s,{action:'invoiceClose',id:b.id,version:b.version,confirmedCents:5000},u,now).invoices[0].status,'closed')});
test('fatura fechada protege compras; pagamento errado e versão antiga são bloqueados',()=>{let s=purchase(),b=s.invoices[0];s=mutate(s,{action:'invoiceClose',id:b.id,version:b.version,confirmedCents:3000},u,now);b=s.invoices[0];assert.throws(()=>mutate(s,{action:'deleteEntry',id,version:1},u,now));assert.throws(()=>mutate(s,{action:'invoicePay',id:b.id,version:b.version,confirmedCents:3000,accountId:'foreign',paidDate:'2026-11-13'},u,now));assert.throws(()=>mutate(s,{action:'invoicePay',id:b.id,version:1,confirmedCents:3000,accountId,paidDate:'2026-11-13'},u,now),x=>x.status===409);s=mutate(s,{action:'invoiceReopen',id:b.id,version:b.version},u,now);assert.equal(mutate(s,{action:'deleteEntry',id,version:1},u,now).entries[0].deleted,true)});
test('desfazer pagamento restaura saldo e pendência sem apagar compras',()=>{let s=purchase(),b=s.invoices[0];s=mutate(s,{action:'invoiceClose',id:b.id,version:b.version,confirmedCents:3000},u,now);b=s.invoices[0];s=mutate(s,{action:'invoicePay',id:b.id,version:b.version,confirmedCents:3000,accountId,paidDate:'2026-11-13'},u,now);b=s.invoices[0];s=mutate(s,{action:'invoiceUndoPay',id:b.id,version:b.version},u,now);assert.equal(summarize(s,'2026-11').balance,100000);assert.equal(summarize(s,'2026-11').payable,3000);assert.equal(s.entries.length,1)});
test('virada de mês, ano, fevereiro e compra depois do fechamento',()=>{assert.deepEqual(invoiceDates(card,'2026-12'),{closeDate:'2026-12-29',dueDate:'2027-01-13'});assert.equal(purchaseCycle('2026-10-30',card),'2026-11');assert.equal(invoiceDates({...card,closingDay:31},'2027-02').closeDate,'2027-02-28');assert.equal(purchaseCycle('2026-10-29',card,[{id:invoiceId(cardId,'2026-10'),status:'closed',closeDate:'2026-10-29'}]),'2026-11')});
test('cartão/fatura de outro financeiro rejeitados e estado antigo preservado',()=>{assert.throws(()=>mutate(empty,{action:'entry',id,createOnly:true,entry:{...e,cardId:'foreign'}},u,now));assert.throws(()=>mutate(empty,{action:'entry',id,createOnly:true,entry:{...e,invoiceId:'foreign_2026-10'}},u,now));assert.equal(empty.entries.length,0);assert.equal(empty.invoices.length,0);assert.equal(purchase().accounts[0].openingCents,100000)});

test('fatura zero exige conferir e não cria débito ou conta pagadora',()=>{let s=mutate(empty,{action:'ensureInvoices'},u,now),b=s.invoices[0];s=mutate(s,{action:'invoiceClose',id:b.id,version:b.version,confirmedCents:0},u,now);assert.equal(s.invoices[0].status,'paid');assert.equal(s.invoices[0].accountId,null);assert.equal(summarize(s,'2026-10').balance,100000)});
