import {test} from 'node:test';import assert from 'node:assert/strict';import {descriptionSpendingReply} from '../../../clientes/financeiro-luciano-yasmin/description-query.js';
const item=(more={})=>({kind:'expense',cents:5000,description:'Gasto na lavoura perto do rio',status:'pending',date:'2026-10-06',dueDate:'2026-10-07',accountId:'a',...more});
const data={accounts:[{id:'a',name:'Dinheiro'}],cards:[{id:'c',name:'Sicredi'}],entries:[item(),item({cents:3000,status:'paid',cardId:'c',description:'Sementes na LAVOURA - PERTO DO RIO'}),item({cents:1000,date:'2026-09-06',description:'Adubo na lavoura perto do rio'}),item({description:'Lavoura perto da estrada',cents:99000}),item({deleted:true,description:'Excluído na lavoura perto do rio',cents:99000}),item({kind:'income',description:'Receita na lavoura perto do rio',cents:99000})]};
test('pergunta exata lista somente a descrição solicitada e soma cada despesa uma vez',()=>{const before=JSON.stringify(data),r=descriptionSpendingReply('quanto eu gastei na lavoura perto do rio',data,'2026-10-06').text;assert.match(r,/TOTAL REGISTRADO: R\$\s*90,00/);assert.match(r,/Sementes/);assert.match(r,/Adubo/);assert.match(r,/a pagar em 07\/10\/2026/);assert.match(r,/Inclui os gastos acima ainda a pagar/);assert.doesNotMatch(r,/estrada|Excluído|Receita/);assert.equal(JSON.stringify(data),before)});
test('período explícito filtra a data da despesa e ausência não retorna total de outros gastos',()=>{assert.match(descriptionSpendingReply('quanto gastei na lavoura perto do rio neste mês',data,'2026-10-06').text,/80,00/);assert.match(descriptionSpendingReply('quanto gastei na lavoura perto do rio no mês passado',data,'2026-10-06').text,/10,00/);assert.match(descriptionSpendingReply('quanto gastei na lavoura perto da ponte',data,'2026-10-06').text,/Nenhum gasto[\s\S]*0,00/)});
test('perguntas de cartão, limite, totais e lançamentos permanecem nas rotas existentes',()=>{for(const q of ['quanto gastei nos cartões','quanto gastei em dinheiro','quanto gastei no total','quanto gastei ao todo entre cartão e outras despesas esse mês','quanto tenho de limite nos cartões','gastei 50 na lavoura perto do rio'])assert.equal(descriptionSpendingReply(q,data,'2026-10-06'),null,q)});

const farm={accounts:data.accounts,cards:[],entries:[item({description:'Compra de veneno',cents:1000,date:'2026-09-02'}),item({description:'Venenos para lavoura',cents:2000,date:'2026-10-01'}),item({description:'Veneno perto do rio',cents:3000,date:'2026-10-06'}),item({description:'Compra de sementes',cents:4000,date:'2026-10-04'}),item({description:'Semente de milho',cents:5000,date:'2026-09-29'}),item({description:'Outro produto venenoso',cents:99000}),item({description:'Veneno excluído',deleted:true,cents:99000})]};
test('formas naturais de perguntar reconhecem item e singular/plural sem somar outras descrições',()=>{for(const q of ['quanto de veneno eu gastei','quanto gastei de veneno','me mostre os gastos com veneno','total gasto em veneno']){const r=descriptionSpendingReply(q,farm,'2026-10-06');assert.match(r.text,/TOTAL REGISTRADO: R\$\s*60,00/);assert.doesNotMatch(r.text,/sementes|venenoso|excluído/);}const seeds=descriptionSpendingReply('quanto de semente gastei',farm,'2026-10-06');assert.match(seeds.text,/TOTAL REGISTRADO: R\$\s*90,00/);assert.match(seeds.text,/Compra de sementes/);assert.match(seeds.text,/Semente de milho/)});
test('intervalos inclusive, mês nomeado, mês numérico, últimos dias e continuação de conversa',()=>{for(const q of ['quanto de veneno gastei de 01/10/2026 até 05/10/2026','quanto gastei com veneno entre 01/10 e 05/10'])assert.match(descriptionSpendingReply(q,farm,'2026-10-06').text,/TOTAL REGISTRADO: R\$\s*20,00/);for(const q of ['quanto de veneno gastei em setembro de 2026','quanto gastei com veneno no mês de setembro','quanto gastei em veneno em 09/2026'])assert.match(descriptionSpendingReply(q,farm,'2026-10-06').text,/TOTAL REGISTRADO: R\$\s*10,00/);assert.match(descriptionSpendingReply('quanto de veneno gastei nos últimos 7 dias',farm,'2026-10-06').text,/TOTAL REGISTRADO: R\$\s*50,00/);assert.match(descriptionSpendingReply('e no mês passado?',farm,'2026-10-06','veneno').text,/TOTAL REGISTRADO: R\$\s*10,00/);assert.match(descriptionSpendingReply('e em outubro?',farm,'2026-10-06','semente').text,/TOTAL REGISTRADO: R\$\s*40,00/)});
test('período inválido ou incompleto não devolve soma geral silenciosamente',()=>{for(const q of ['quanto gastei em veneno de 31/02/2026 até 05/03/2026','quanto gastei em veneno de 10/10/2026 até 01/10/2026','quanto de veneno gastei desde 01/10','quanto gastei em veneno nos últimos 0 dias']){const r=descriptionSpendingReply(q,farm,'2026-10-06');assert.ok(r);assert.doesNotMatch(r.text,/TOTAL REGISTRADO/);assert.match(r.text,/período/);}});
