import {test} from 'node:test';import assert from 'node:assert/strict';import {mutate,summarize,validDate} from '../ledger.js';import {parseMessage,moneyCents} from '../../../clientes/financeiro-luciano-yasmin/conversation.js';
const user={name:'Luciano'},account='00000000-0000-4000-8000-000000000001',id='00000000-0000-4000-8000-000000000002';
const initial={accounts:[{id:account,name:'Sicredi',openingCents:100000,version:1}],entries:[]};const fields={kind:'expense',cents:8550,description:'Mercado',category:'Alimentação',accountId:account,date:'2026-10-06',dueDate:'2026-10-07',status:'pending',scope:'casal'};
test('valores brasileiros, centavos e calendário',()=>{assert.equal(moneyCents('R$ 1.234,56'),123456);assert.equal(moneyCents('0,01'),1);assert.equal(moneyCents('-50,00'),-5000);assert.equal(moneyCents('85.50'),8550);assert.equal(moneyCents('abc'),null);assert.equal(validDate('2026-02-30'),false)});
test('interpreta despesa paga, receita pendente, conta e data',()=>{const a=parseMessage('Paguei R$ 85,50 no mercado hoje no Sicredi',[initial.accounts[0]],'2026-10-06');assert.equal(a.cents,8550);assert.equal(a.kind,'expense');assert.equal(a.status,'paid');assert.equal(a.accountId,account);assert.equal(a.category,'Alimentação');const b=parseMessage('Tenho R$ 500 a receber amanhã',initial.accounts,'2026-10-06');assert.equal(b.kind,'income');assert.equal(b.status,'pending');assert.equal(b.dueDate,'2026-10-07');assert.equal(parseMessage('gastei 50 reais no mercado',initial.accounts,'2026-10-06').status,undefined)});
test('pendência não altera saldo; pagamento, exclusão e restauração corrigem totais',()=>{let s=mutate(initial,{action:'entry',id,createOnly:true,entry:fields},user);assert.equal(summarize(s,'2026-10').balance,100000);assert.equal(summarize(s,'2026-10').payable,8550);s=mutate(s,{action:'settleEntry',id,version:1,paidDate:'2026-10-07'},user);assert.equal(summarize(s,'2026-10').balance,91450);assert.equal(summarize(s,'2026-10').expense,8550);s=mutate(s,{action:'deleteEntry',id,version:2},user);assert.equal(summarize(s,'2026-10').balance,100000);s=mutate(s,{action:'restoreEntry',id,version:3},user);assert.equal(summarize(s,'2026-10').balance,91450);assert.equal(initial.entries.length,0)});
test('nova tentativa não duplica e edição antiga é bloqueada',()=>{const p={action:'entry',id,createOnly:true,entry:fields};const s=mutate(initial,p,user);assert.equal(mutate(s,p,user).entries.length,1);assert.throws(()=>mutate(s,{...p,entry:{...fields,cents:100}},user),e=>e.status===409);assert.throws(()=>mutate(s,{action:'entry',id,version:0,entry:fields},user),e=>e.status===409)});
test('conta de outro financeiro e valores inválidos são rejeitados',()=>{assert.throws(()=>mutate(initial,{action:'entry',id,createOnly:true,entry:{...fields,accountId:'another-space'}},user));assert.throws(()=>mutate(initial,{action:'entry',id,createOnly:true,entry:{...fields,cents:0}},user));assert.throws(()=>mutate(initial,{action:'entry',id,createOnly:true,entry:{...fields,cents:85.5}},user))});
test('receita recebida entra no saldo no mês correto',()=>{const s=mutate(initial,{action:'entry',id,createOnly:true,entry:{...fields,kind:'income',status:'paid',paidDate:'2026-11-01'}},user);assert.equal(summarize(s,'2026-10').income,0);assert.equal(summarize(s,'2026-11').income,8550);assert.equal(summarize(s,'2026-10').balance,108550)});
