import {test} from 'node:test';
import assert from 'node:assert/strict';
import {monthlySpendingReply} from '../../../clientes/financeiro-luciano-yasmin/spending-query.js';
const accounts=[{id:'cash',name:'Dinheiro em casa'},{id:'bank',name:'Sicredi'},{id:'old',name:'Nubank',deleted:true}];
const item=(cents,more={})=>({kind:'expense',cents,date:'2026-10-06',paidDate:'2026-10-06',status:'paid',accountId:'bank',...more});
const data={accounts,cards:[{name:'Sicredi',id:'card'}],entries:[item(10000,{cardId:'card',status:'pending',paidDate:null}),item(12000,{cardId:'card'}),item(20000,{cardId:'card',date:'2026-09-20'}),item(3000,{accountId:'cash'}),item(4000),item(1000,{accountId:'old'}),item(1000,{accountId:'missing'}),item(4000,{status:'pending',dueDate:'2026-10-20',paidDate:null}),item(99900,{deleted:true}),item(99900,{kind:'income'}),item(9000,{paidDate:'2026-09-30'})]};
test('pergunta exata separa cartão, dinheiro e banco com total e pendências à parte',()=>{const before=JSON.stringify(data);const r=monthlySpendingReply('QUANTO EU GASTEI AO TODO ENTRE CARTÃO E OUTRAS DESPESAS ESSE MES',data,'2026-10-06');assert.match(r.text,/Cartão de crédito: R\$\s*220,00/);assert.match(r.text,/Dinheiro: R\$\s*30,00/);assert.match(r.text,/Banco \/ outras contas: R\$\s*50,00/);assert.match(r.text,/Conta não identificada: R\$\s*10,00/);assert.match(r.text,/TOTAL GERAL: R\$\s*310,00/);assert.match(r.text,/a pagar neste mês: R\$\s*40,00/);assert.match(r.text,/Nubank: R\$\s*10,00/);assert.equal(JSON.stringify(data),before)});
test('compras no cartão não contam novamente na conta que pagou a fatura',()=>{const pending={...data,entries:[item(10000,{cardId:'card',status:'pending',paidDate:null})]};const paid={...pending,entries:[item(10000,{cardId:'card',accountId:'bank'})]};for(const s of [pending,paid]){assert.match(monthlySpendingReply('quanto gastei esse mês',s,'2026-10-06').text,/TOTAL GERAL: R\$\s*100,00/);assert.match(monthlySpendingReply('quanto gastei esse mês',s,'2026-10-06').text,/Banco \/ outras contas: R\$\s*0,00/)}assert.match(monthlySpendingReply('quanto gastei no mês passado',data,'2026-10-06').text,/TOTAL GERAL: R\$\s*290,00/)});
test('consulta geral preserva consultas só do cartão, limites, categorias e lançamentos',()=>{for(const text of ['quanto gastei no cartão de crédito','quanto gastei no cartão Sicredi neste mês','quanto de limite tem no cartão','quanto gastei no mercado','quanto recebi esse mês','gastei 50 no mercado'])assert.equal(monthlySpendingReply(text,data,'2026-10-06'),null,text);for(const text of ['quanto gastei esse mês','mostre meus gastos do mês','quanto gastei ao todo','quanto gastei no cartão e em dinheiro e no banco'])assert.ok(monthlySpendingReply(text,data,'2026-10-06'),text);assert.match(monthlySpendingReply('quanto gastei esse mês',{accounts:[],entries:[]},'2026-10-06').text,/TOTAL GERAL: R\$\s*0,00/)});
