import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import {mutate} from '../ledger.js';
const html=readFileSync('clientes/financeiro-luciano-yasmin/index.html','utf8'),map=new Map();
let scrolls=0;globalThis.requestAnimationFrame=fn=>{fn();return 1};
class Element{constructor(id){this.id=id;this.value='';this.hidden=false;this.open=false;this.classList={toggle(){},add(){},remove(){}};this.dataset={};}addEventListener(){}focus(){}select(){}setSelectionRange(){}scrollIntoView(){scrolls++}showModal(){this.open=true}close(){this.open=false}set innerHTML(s){this.html=s;if(this.id==='content')for(const id of [...map.keys()])if(!html.includes('id="'+id+'"'))map.delete(id);for(const m of s.matchAll(/id="([^"]+)"/g))if(!map.has(m[1]))map.set(m[1],new Element(m[1]));const option=s.match(/<option[^>]*value="([^"]+)"/);if(option)this.value=option[1];}get innerHTML(){return this.html||''}}
for(const m of html.matchAll(/id="([^"]+)"/g))map.set(m[1],new Element(m[1]));
globalThis.document={getElementById:id=>map.get(id)||null,querySelectorAll:()=>[],querySelector:()=>new Element('compose'),activeElement:null,addEventListener(){},hidden:false};globalThis.window={addEventListener(){},scrollTo(){}};Object.defineProperty(globalThis,'navigator',{value:{},configurable:true});globalThis.localStorage={getItem:()=>null,setItem(){},removeItem(){}};globalThis.setInterval=()=>0;globalThis.alert=()=>{};globalThis.confirm=()=>true;
let db={accounts:[{id:'00000000-0000-4000-8000-000000000001',name:'Conta Sicredi',openingCents:100000,version:1}],entries:[],cards:[{id:'00000000-0000-4000-8000-000000000010',name:'Sicredi',closingDay:29,dueDay:13,version:1}],invoices:[]};let calls=[];
globalThis.fetch=async(url,options)=>{const p=JSON.parse(options.body);calls.push(p.action);try{if(p.action==='state')return {ok:true,json:async()=>({data:structuredClone(db),user:{id:'test-user',name:'Luciano'}})};db=mutate(db,p,{name:'Luciano'},'2026-10-06T15:00:00Z');return {ok:true,json:async()=>({data:structuredClone(db)})}}catch(e){return{ok:false,status:e.status||400,json:async()=>({message:e.message})}}};
let source=readFileSync('clientes/financeiro-luciano-yasmin/app.js','utf8').replaceAll("from './","from '../../../clientes/financeiro-luciano-yasmin/");source+='\nexport const t={sendMessage,announceInvoices,openEntry,startCredit,handleCreditReply,choosePayAccount,go,render, set(s){state=s;user={id:"test-user",name:"Luciano"}},get(){return {state,draft,creditFlow}},money};';writeFileSync('backend/lt-meu-financeiro/tests/.ui-test-app.js',source);const {t}=await import('./.ui-test-app.js');t.set(structuredClone(db));t.render();
const initialScroll=scrolls;await t.sendMessage('Gastei 30,00 com recarda do celular no cartão de crédito Sicredi');assert.ok(scrolls>initialScroll,'nova mensagem rola para o fim');assert.ok(map.get('content').innerHTML.includes('Na fatura com vencimento para 13/11/2026'));assert.equal(t.get().draft.cardId,db.cards[0].id);assert.equal(t.get().draft.cents,3000);assert.equal(calls.length,0,'mensagem não salva sem confirmação');t.openEntry(t.get().draft,true);assert.equal(map.get('entryPayment').value,'credit');assert.equal(map.get('entryAccount').disabled,true);assert.equal(map.get('entryStatus').value,'pending');assert.equal(map.get('entryDue').value,'2026-11-13');await map.get('editForm').onsubmit({preventDefault(){}});assert.equal(db.entries.length,1);assert.equal(db.entries[0].accountId,null);const id=db.invoices[0].id;
t.startCredit(id);await t.handleCreditReply('sim');assert.equal(t.get().creditFlow.stage,'bankTotal');await t.handleCreditReply('50,00');assert.equal(t.get().creditFlow.stage,'finding');assert.equal(db.invoices[0].bankCents,5000);assert.ok(t.get().creditFlow.question.includes('Divergência de'));assert.ok(t.get().creditFlow.question.includes('20,00'));await t.sendMessage('Faltou 20,00 de tarifa');t.openEntry(t.get().draft,true);await map.get('editForm').onsubmit({preventDefault(){}});assert.equal(db.entries.length,2);assert.equal(t.get().creditFlow.stage,'confirmClose');await t.handleCreditReply('confirmar');assert.equal(db.invoices[0].status,'closed');
t.startCredit(id,true);await t.handleCreditReply('sim');t.choosePayAccount(db.accounts[0].id);assert.equal(t.get().creditFlow.stage,'payConfirm');await t.handleCreditReply('confirmar');assert.equal(db.invoices[0].status,'paid');assert.equal(db.entries.filter(e=>e.status==='paid').length,2);assert.equal(db.accounts[0].openingCents,100000);
for(const tab of ['chat','summary','entries','cards','accounts'])t.go(tab);console.log('OK: mensagem do usuário, revisão sem salvar, cartão no editor, diferença, compra faltante, fechamento, conta pagadora, pagamento e cinco telas.');

const reminderState={accounts:db.accounts,entries:[],cards:[{...db.cards[0],closingDay:5,dueDay:13}],invoices:[{...db.invoices[0],id:db.cards[0].id+'_2026-10',closeDate:'2026-10-05',status:'open',bankCents:null,version:1}]};t.set(reminderState);t.go('chat');t.announceInvoices();assert.equal(t.get().creditFlow.stage,'closedQuestion');console.log('OK: pergunta automática de fechamento no chat, inclusive fatura ainda sem compras.');

const prior={...reminderState,invoices:[{...reminderState.invoices[0],bankCents:3000}]};t.set(prior);t.startCredit(prior.invoices[0].id);await t.handleCreditReply('sim');assert.equal(t.get().creditFlow.stage,'finding');assert.ok(t.get().creditFlow.question.includes('Divergência de'));const before=scrolls;await t.sendMessage('cancelar');await t.sendMessage('Qual meu saldo?');assert.ok(scrolls>before,'respostas e cancelamentos também rolam');console.log('OK: divergência conhecida reaparece, banco é obrigatório para comparação e rolagem cobre consultas.');
