import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import {mutate} from '../ledger.js';
const html=readFileSync('clientes/financeiro-luciano-yasmin/index.html','utf8'),map=new Map();
const realSetTimeout=globalThis.setTimeout;let replyDelays=0;globalThis.setTimeout=(fn,ms,...args)=>{if(ms===3000){replyDelays++;return realSetTimeout(fn,0,...args)}return realSetTimeout(fn,ms,...args)};
const events=new Map();let scrolls=0;let messageBottom=1400;const layout={style:{}};const stream={lastElementChild:{getBoundingClientRect:()=>({bottom:messageBottom-window.scrollY})}};globalThis.requestAnimationFrame=fn=>{fn();return 1};
class Element{constructor(id){this.id=id;this.value='';this.hidden=false;this.open=false;this.classList={toggle(){},add(){},remove(){}};this.dataset={};}addEventListener(){}focus(){}select(){}setSelectionRange(){}scrollIntoView(){scrolls++}showModal(){this.open=true}close(){this.open=false}set innerHTML(s){this.html=s;if(this.id==='content')for(const id of [...map.keys()])if(!html.includes('id="'+id+'"'))map.delete(id);for(const m of s.matchAll(/id="([^"]+)"/g))if(!map.has(m[1]))map.set(m[1],new Element(m[1]));const option=s.match(/<option[^>]*value="([^"]+)"/);if(option)this.value=option[1];}get innerHTML(){return this.html||''}}
for(const m of html.matchAll(/id="([^"]+)"/g))map.set(m[1],new Element(m[1]));
globalThis.document={getElementById:id=>map.get(id)||null,querySelectorAll:()=>[],querySelector:selector=>selector==='.chat-stream'?stream:selector==='.chat-layout'?layout:selector==='.chat-compose'?{getBoundingClientRect:()=>({height:70})}:selector==='.bottom-nav'?{getBoundingClientRect:()=>({height:80})}:null,activeElement:null,addEventListener(type,fn){const key='document:'+type,prev=events.get(key);events.set(key,prev?()=>{prev();fn()}:fn)},hidden:false};globalThis.window={innerHeight:900,scrollY:0,addEventListener(type,fn){events.set('window:'+type,fn)},scrollTo({top}){this.scrollY=top;scrolls++}};Object.defineProperty(globalThis,'navigator',{value:{},configurable:true});globalThis.localStorage={getItem:()=>null,setItem(){},removeItem(){}};globalThis.setInterval=()=>0;globalThis.alert=()=>{};globalThis.confirm=()=>true;
let db={accounts:[{id:'00000000-0000-4000-8000-000000000001',name:'Conta Sicredi',openingCents:100000,version:1}],entries:[],cards:[{id:'00000000-0000-4000-8000-000000000010',name:'Sicredi',closingDay:29,dueDay:13,version:1}],invoices:[]};let calls=[];
globalThis.fetch=async(url,options)=>{const p=JSON.parse(options.body);if(!p.action.startsWith('chat'))calls.push(p.action);try{if(p.action==='chatAppend')return {ok:true,json:async()=>({ok:true})};if(p.action==='chatState')return {ok:true,json:async()=>({messages:[],hasOlder:false,before:null})};if(p.action==='state')return {ok:true,json:async()=>({data:structuredClone(db),user:{id:'test-user',name:'Luciano'}})};db=mutate(db,p,{name:'Luciano'},'2026-10-06T15:00:00Z');return {ok:true,json:async()=>({data:structuredClone(db)})}}catch(e){return{ok:false,status:e.status||400,json:async()=>({message:e.message})}}};
let source=readFileSync('clientes/financeiro-luciano-yasmin/app.js','utf8').replaceAll("from './","from '../../../clientes/financeiro-luciano-yasmin/");source+='\nexport const t={voice,openVoice,closeVoice,sendMessage,announceInvoices,openEntry,startCredit,handleCreditReply,choosePayAccount,go,render,scrollChatLatest,fitChatViewport,refresh,budgetWrite,startDueReminder,handleDueReply,announceEntryReminders, clearFlows(){draft=null;creditFlow=null;dueFlow=null}, prepareOpening(){auth={token:"test-token"};user=null;messages=[];creditFlow=null;chatNeedsScroll=false;$("shell").hidden=true}, set(s){state=s;user={id:"test-user",name:"Luciano"}},get(){return {state,draft,creditFlow,messages,dueFlow}},money};';writeFileSync('backend/lt-meu-financeiro/tests/.ui-test-app.js',source);const {t}=await import('./.ui-test-app.js');t.set(structuredClone(db));t.render();
const initialScroll=scrolls;await t.sendMessage('Gastei 30,00 com recarda do celular no cartão de crédito Sicredi');assert.ok(scrolls>initialScroll,'nova mensagem rola para o fim');assert.ok(map.get('content').innerHTML.includes('Na fatura com vencimento para 13/11/2026'));assert.equal(t.get().draft.cardId,db.cards[0].id);assert.equal(t.get().draft.cents,3000);assert.equal(calls.length,0,'mensagem não salva sem confirmação');t.openEntry(t.get().draft,true);assert.equal(map.get('entryPayment').value,'credit');assert.equal(map.get('entryAccount').disabled,true);assert.equal(map.get('entryStatus').value,'pending');assert.equal(map.get('entryDue').value,'2026-11-13');await map.get('editForm').onsubmit({preventDefault(){}});assert.equal(db.entries.length,1);assert.equal(db.entries[0].accountId,null);const id=db.invoices[0].id;
t.startCredit(id);await t.handleCreditReply('sim');assert.equal(t.get().creditFlow.stage,'bankTotal');await t.handleCreditReply('50,00');assert.equal(t.get().creditFlow.stage,'finding');assert.equal(db.invoices[0].bankCents,5000);assert.ok(t.get().creditFlow.question.includes('Divergência de'));assert.ok(t.get().creditFlow.question.includes('20,00'));await t.sendMessage('Faltou 20,00 de tarifa');t.openEntry(t.get().draft,true);await map.get('editForm').onsubmit({preventDefault(){}});assert.equal(db.entries.length,2);assert.equal(t.get().creditFlow.stage,'confirmClose');await t.handleCreditReply('confirmar');assert.equal(db.invoices[0].status,'closed');
t.startCredit(id,true);await t.handleCreditReply('sim');t.choosePayAccount(db.accounts[0].id);assert.equal(t.get().creditFlow.stage,'payConfirm');await t.handleCreditReply('confirmar');assert.equal(db.invoices[0].status,'paid');assert.equal(db.entries.filter(e=>e.status==='paid').length,2);assert.equal(db.accounts[0].openingCents,100000);
for(const tab of ['chat','summary','entries','cards','accounts'])t.go(tab);console.log('OK: mensagem do usuário, revisão sem salvar, cartão no editor, diferença, compra faltante, fechamento, conta pagadora, pagamento e cinco telas.');

const reminderState={accounts:db.accounts,entries:[],cards:[{...db.cards[0],closingDay:5,dueDay:13}],invoices:[{...db.invoices[0],id:db.cards[0].id+'_2026-10',closeDate:'2026-10-05',status:'open',bankCents:null,version:1}]};t.set(reminderState);t.go('chat');t.announceInvoices();assert.equal(t.get().creditFlow.stage,'closedQuestion');console.log('OK: pergunta automática de fechamento no chat, inclusive fatura ainda sem compras.');

const prior={...reminderState,invoices:[{...reminderState.invoices[0],bankCents:3000}]};t.set(prior);t.startCredit(prior.invoices[0].id);await t.handleCreditReply('sim');assert.equal(t.get().creditFlow.stage,'finding');assert.ok(t.get().creditFlow.question.includes('Divergência de'));const before=scrolls;await t.sendMessage('cancelar');await t.sendMessage('Qual meu saldo?');assert.ok(scrolls>before,'respostas e cancelamentos também rolam');console.log('OK: divergência conhecida reaparece, banco é obrigatório para comparação e rolagem cobre consultas.');

const limits={...db,cards:[{...db.cards[0],limitCents:100000}]};t.set(limits);const beforeQueryCalls=calls.length,beforeQueryEntries=JSON.stringify(limits.entries);await t.sendMessage('quanto de limite tem no cartão');assert.equal(calls.length,beforeQueryCalls);assert.equal(JSON.stringify(t.get().state.entries),beforeQueryEntries);assert.equal(t.get().draft,null);assert.ok(map.get('content').innerHTML.includes('Limite disponível no cartão'));console.log('OK: pergunta sobre limite responde sem iniciar ou salvar lançamento.');

// Real geometry: a visible sticky composer must not prevent an off-screen reply from being scrolled into view.
for(const height of [900,740,600]){window.innerHeight=height;window.visualViewport=undefined;window.scrollY=0;messageBottom=2400;t.go('chat');assert.equal(window.scrollY,2400-(height-80-70-32));assert.ok(messageBottom-window.scrollY<=height-80-70-32);}
window.innerHeight=800;window.visualViewport={height:450,offsetTop:0};window.scrollY=0;messageBottom=2600;t.scrollChatLatest();assert.equal(window.scrollY,2332);assert.equal(layout.style.paddingBottom,'350px');assert.equal(messageBottom-window.scrollY,268,'resposta acima do teclado e da caixa de mensagem');
messageBottom=3400;t.scrollChatLatest();assert.equal(window.scrollY,3132,'nova resposta longa acompanha a conversa');t.go('summary');const offChat=scrolls;t.scrollChatLatest();assert.equal(scrolls,offChat,'outras telas não são roladas pelo chat');window.visualViewport=undefined;console.log('OK: posição da última resposta em PC, tablet, celular e teclado aberto; outras telas preservadas.');

// Opening with saved messages adds no new bubble: it still must land at the last saved message.
db={...db,cards:[],invoices:[]};const savedMessages=[{role:'bot',text:'Última mensagem já salva',time:'2026-10-06T12:00:00Z'}];localStorage.getItem=()=>JSON.stringify(savedMessages);t.go('chat');t.prepareOpening();window.scrollY=0;messageBottom=4200;const openingScrolls=scrolls;await t.refresh();assert.ok(scrolls>openingScrolls);assert.ok(map.get('content').innerHTML.includes('Última mensagem já salva'));assert.equal(window.scrollY,4200-(window.innerHeight-80-70-32));
window.scrollY=0;events.get('window:pageshow')();assert.equal(window.scrollY,4200-(window.innerHeight-80-70-32),'restauração da página abre na última mensagem');window.scrollY=0;events.get('document:visibilitychange')();assert.equal(window.scrollY,4200-(window.innerHeight-80-70-32),'voltar ao aplicativo mostra a última mensagem');await new Promise(resolve=>setImmediate(resolve));t.go('summary');const beforeResume=scrolls;events.get('window:pageshow')();assert.equal(scrolls,beforeResume,'retomar outra tela não força a conversa');console.log('OK: abertura com histórico salvo, restauração e retorno ao aplicativo posicionam a última mensagem.');

const spendState={accounts:db.accounts,cards:[{id:'spend-card',name:'Sicredi',closingDay:29,dueDay:13}],invoices:[],entries:[{id:'spend-item',cardId:'spend-card',invoiceId:'spend-card_2026-10',kind:'expense',cents:12345,status:'pending',date:'2026-10-06'}]};t.set(spendState);t.go('chat');const spendCalls=calls.length,spendEntries=JSON.stringify(t.get().state.entries),spendDraft=t.get().draft;await t.sendMessage('quanto gastei no cartão de crédito');assert.ok(map.get('content').innerHTML.includes('123,45'));assert.ok(map.get('content').innerHTML.includes('Total de compras no cartão de crédito'));assert.equal(calls.length,spendCalls);assert.equal(JSON.stringify(t.get().state.entries),spendEntries);assert.equal(t.get().draft,spendDraft);console.log('OK: consulta de compras no crédito responde sem gravar ou iniciar lançamento.');

const monthlyState={...spendState,accounts:[...spendState.accounts,{id:'cash',name:'Dinheiro'}],entries:[...spendState.entries,{id:'cash-item',accountId:'cash',kind:'expense',cents:3000,date:'2026-10-06',paidDate:'2026-10-06',status:'paid'},{id:'bank-item',accountId:spendState.accounts[0].id,kind:'expense',cents:5000,date:'2026-10-06',paidDate:'2026-10-06',status:'paid'}]};t.set(monthlyState);const monthlyCalls=calls.length,monthlyEntries=JSON.stringify(t.get().state.entries),monthlyDraft=t.get().draft;await t.sendMessage('QUANTO EU GASTEI AO TODO ENTRE CARTÃO E OUTRAS DESPESAS ESSE MES');assert.ok(map.get('content').innerHTML.includes('TOTAL GERAL:'));assert.ok(map.get('content').innerHTML.includes('203,45'));assert.ok(map.get('content').innerHTML.includes('Cartão de crédito:'));assert.ok(map.get('content').innerHTML.includes('Dinheiro:'));assert.ok(map.get('content').innerHTML.includes('Banco / outras contas:'));assert.equal(calls.length,monthlyCalls);assert.equal(JSON.stringify(t.get().state.entries),monthlyEntries);assert.equal(t.get().draft,monthlyDraft);console.log('OK: pergunta exata do usuário responde total mensal dividido por forma de pagamento, sem alterar lançamentos.');

// Optional budgets can be activated and saved without altering transactions.
db=structuredClone(monthlyState);db.entries[0].description='Gasolina';db.entries[0].category='Transporte';t.set(structuredClone(db));t.go('budgets');assert.ok(map.get('content').innerHTML.includes('Desativado'));await map.get('budgetToggle').onclick();assert.equal(db.budgetSettings.enabled,true);map.get('budgetCategory').value='Combustível';map.get('budgetAmount').value='100,00';await map.get('budgetForm').onsubmit({preventDefault(){}});await new Promise(resolve=>setImmediate(resolve));assert.equal(db.budgets[0].limitCents,10000);assert.equal(db.budgetAlerts[0].excessCents,2345);t.go('chat');const budgetQueries=calls.length;await t.sendMessage('quanto ainda posso gastar de combustível');assert.ok(map.get('content').innerHTML.includes('23,45'));assert.equal(calls.length,budgetQueries);const budgetEntries=JSON.stringify(db.entries);await t.budgetWrite({action:'budgetResponse',id:db.budgetAlerts[0].id,version:0,response:'note',note:'Viagem extra'});assert.equal(db.budgetAlerts[0].note,'Viagem extra');assert.equal(JSON.stringify(db.entries),budgetEntries);t.go('budgets');assert.ok(map.get('content').innerHTML.includes('Viagem extra'));console.log('OK: ativação opcional, limite, aviso no chat, consulta e justificativa salva sem alterar lançamentos.');

const multipleCards={...t.get().state,cards:[{id:'limit-a',name:'Sicredi',limitCents:100000},{id:'limit-b',name:'Nubank',limitCents:200000}],entries:[{cardId:'limit-a',cents:3000,status:'pending'},{cardId:'limit-b',cents:5000,status:'pending'}]};t.set(multipleCards);t.go('chat');const pluralCalls=calls.length,pluralEntries=JSON.stringify(t.get().state.entries),pluralDraft=t.get().draft;await t.sendMessage('QUANTO TENHO DE LIMITE NOS CARTÕES');assert.ok(map.get('content').innerHTML.includes('Limites por cartão:'));assert.ok(map.get('content').innerHTML.includes('970,00'));assert.ok(map.get('content').innerHTML.includes('1.950,00'));assert.equal(calls.length,pluralCalls);assert.equal(JSON.stringify(t.get().state.entries),pluralEntries);assert.equal(t.get().draft,pluralDraft);console.log('OK: pergunta plural lista limites de todos os cartões sem iniciar ou salvar lançamento.');

const beforeTypingCalls=calls.length,beforeDelay=replyDelays;const pendingReply=t.sendMessage('quanto tenho de limite nos cartões');assert.ok(map.get('content').innerHTML.includes('Meu Financeiro está digitando…'));assert.equal(map.get('chatSend').disabled,true);const retryText='Texto para a próxima pergunta';map.get('chatText').value=retryText;await t.sendMessage('Mensagem repetida enquanto aguarda');assert.equal(replyDelays,beforeDelay+1,'uma resposta de cada vez');assert.equal(map.get('chatText').value,retryText);await pendingReply;assert.ok(!map.get('content').innerHTML.includes('Meu Financeiro está digitando…'));assert.equal(map.get('chatSend').disabled,false);assert.equal(map.get('chatText').value,retryText,'digitação seguinte preservada');assert.equal(calls.length,beforeTypingCalls);console.log('OK: espera de 3000 ms, indicador de digitação, bloqueio de envio repetido e texto seguinte preservado.');

const accountState={accounts:[{id:'sicredi',name:'SICREDI',openingCents:100000},{id:'nubank',name:'Nubank',openingCents:900000}],entries:[{accountId:'sicredi',kind:'expense',status:'paid',cents:5000},{accountId:'sicredi',kind:'expense',status:'pending',cents:10000},{accountId:'sicredi',kind:'income',status:'pending',cents:20000},{accountId:'nubank',kind:'expense',status:'pending',cents:99000}],cards:[],invoices:[]};t.set(accountState);t.go('chat');const accountCalls=calls.length,accountEntries=JSON.stringify(t.get().state.entries);await t.sendMessage('quanto tenho na conta do sicredi');const lastAccountReply=map.get('content').innerHTML.split('<small>Meu Financeiro</small>').pop();assert.ok(lastAccountReply.includes('950,00'));assert.ok(lastAccountReply.includes('200,00'));assert.ok(lastAccountReply.includes('100,00'));assert.ok(!lastAccountReply.includes('Nubank'));assert.equal(calls.length,accountCalls);assert.equal(JSON.stringify(t.get().state.entries),accountEntries);console.log('OK: pergunta sobre conta Sicredi responde saldo e previsões apenas dela, sem alterar dados.');

// Natural scheduling saves the due date only after review, and reminders never settle automatically.
localStorage.getItem=()=>null;db={accounts:[{id:'00000000-0000-4000-8000-000000000001',name:'Dinheiro',openingCents:100000,version:1}],entries:[],cards:[],invoices:[]};t.set(structuredClone(db));t.go('chat');await t.sendMessage('Gastei 50,00 reais na lavoura perto do rio');await t.sendMessage('esta para pagar dia 07/10/2026 consegue me lembrar?');assert.equal(t.get().draft.status,'pending');assert.equal(t.get().draft.date,'2026-10-06');assert.equal(t.get().draft.dueDate,'2026-10-07');assert.equal(t.get().draft.cents,5000);assert.equal(db.entries.length,0);await t.sendMessage('dinheiro');t.openEntry(t.get().draft,true);await map.get('editForm').onsubmit({preventDefault(){}});assert.equal(db.entries[0].status,'pending');assert.equal(db.entries[0].dueDate,'2026-10-07');assert.ok(map.get('content').innerHTML.includes('Lembrete na conversa em 07/10/2026'));const pendingId=db.entries[0].id;t.startDueReminder(pendingId);await t.handleDueReply('ainda não paguei');assert.equal(db.entries[0].status,'pending');t.startDueReminder(pendingId);const beforePaidAnswer=calls.length;await t.handleDueReply('sim, hoje');assert.equal(calls.length,beforePaidAnswer);assert.equal(db.entries[0].status,'pending');await t.handleDueReply('confirmar');assert.equal(db.entries[0].status,'paid');assert.equal(db.entries.length,1);console.log('OK: frase natural agenda 07/10, revisão antes de salvar, lembrete, resposta ainda não e baixa somente com confirmação.');

const dueEntry={...db.entries[0],id:'00000000-0000-4000-8000-000000000091',description:'Conta com vencimento hoje',status:'pending',paidDate:null,dueDate:'2026-10-06'};db.entries.push(dueEntry);t.set(structuredClone(db));t.go('chat');assert.equal(t.get().dueFlow.id,dueEntry.id);const autoReminders=t.get().messages.filter(m=>m.text.includes('🔔 Lembrete: Conta com vencimento hoje')).length;assert.equal(autoReminders,1);t.render();assert.equal(t.get().messages.filter(m=>m.text.includes('🔔 Lembrete: Conta com vencimento hoje')).length,1);assert.equal(db.entries.find(e=>e.id===dueEntry.id).status,'pending');console.log('OK: vencimento do dia anuncia na abertura, não repete a mensagem em cada atualização e não paga automaticamente.');

const beforeReceivable=calls.length;await t.sendMessage('vou receber uma conta dia 07/10 no valor de 50,00');assert.equal(t.get().draft.kind,'income');assert.equal(t.get().draft.status,'pending');assert.equal(t.get().draft.cents,5000);assert.equal(t.get().draft.dueDate,'2026-10-07');assert.equal(calls.length,beforeReceivable);await t.sendMessage('dinheiro');t.openEntry(t.get().draft,true);await map.get('editForm').onsubmit({preventDefault(){}});const receivable=db.entries.find(e=>e.kind==='income');assert.equal(receivable.status,'pending');assert.equal(receivable.cents,5000);assert.equal(receivable.dueDate,'2026-10-07');console.log('OK: frase exata de receita futura interpreta valor e data, pede conta e salva a receber após confirmar.');

const descriptionState={accounts:[{id:'description-cash',name:'Dinheiro',openingCents:0}],cards:[],invoices:[],entries:[{id:'description-entry',kind:'expense',cents:5000,description:'Gasto na lavoura perto do rio',status:'pending',date:'2026-10-06',dueDate:'2026-10-07',accountId:'description-cash'},{id:'other-entry',kind:'expense',cents:99000,description:'Almoço',status:'paid',date:'2026-10-06',paidDate:'2026-10-06',accountId:'description-cash'}]};t.set(descriptionState);t.go('chat');const descriptionCalls=calls.length,descriptionBefore=JSON.stringify(t.get().state.entries);await t.sendMessage('quanto eu gastei na lavoura perto do rio');const descriptionReply=t.get().messages.at(-1).text;assert.ok(descriptionReply.includes('Gasto na lavoura perto do rio'));assert.ok(descriptionReply.includes('TOTAL REGISTRADO:'));assert.ok(descriptionReply.includes('50,00'));assert.ok(!descriptionReply.includes('Almoço'));assert.ok(!descriptionReply.includes('990,00'));assert.equal(calls.length,descriptionCalls);assert.equal(JSON.stringify(t.get().state.entries),descriptionBefore);console.log('OK: pergunta exata sobre lavoura retorna apenas despesas dessa descrição e seu total, sem escrever dados.');

const itemsState={accounts:descriptionState.accounts,cards:[],invoices:[],entries:[{...descriptionState.entries[0],description:'Compra de venenos',cents:2000,date:'2026-10-06'},{...descriptionState.entries[0],id:'old-venom',description:'Veneno para lavoura',cents:1000,date:'2026-09-02'},{...descriptionState.entries[0],id:'seeds',description:'Compra de sementes',cents:4000,date:'2026-10-06'}]};t.set(itemsState);const itemCalls=calls.length;await t.sendMessage('quanto de veneno eu gastei');assert.ok(t.get().messages.at(-1).text.includes('TOTAL REGISTRADO:'));assert.ok(t.get().messages.at(-1).text.includes('30,00'));await t.sendMessage('e no mês passado?');assert.ok(t.get().messages.at(-1).text.includes('10,00'));assert.ok(!t.get().messages.at(-1).text.includes('Compra de venenos'));await t.sendMessage('quanto de semente gastei');assert.ok(t.get().messages.at(-1).text.includes('Compra de sementes'));assert.ok(t.get().messages.at(-1).text.includes('40,00'));assert.equal(calls.length,itemCalls);console.log('OK: veneno/semente, plural e continuação por período respondem na conversa sem alterar dados.');

const uiClasses=new Set(),viewportStyle=new Map();document.body={classList:{toggle(name,on){if(on)uiClasses.add(name);else uiClasses.delete(name)}}};document.documentElement={style:{setProperty:(name,value)=>viewportStyle.set(name,value)}};document.activeElement={id:'chatText'};window.innerHeight=844;window.visualViewport={height:390,offsetTop:80};t.go('chat');t.fitChatViewport();assert.ok(uiClasses.has('chat-keyboard'));assert.equal(viewportStyle.get('--app-height'),'390px');assert.equal(viewportStyle.get('--app-top'),'80px');window.visualViewport={height:844,offsetTop:0};t.fitChatViewport();assert.ok(!uiClasses.has('chat-keyboard'));t.go('summary');window.visualViewport={height:390,offsetTop:0};t.fitChatViewport();assert.ok(!uiClasses.has('chat-keyboard'));console.log('OK: teclado reduzido ativa modo compacto, acompanha deslocamento do iOS e restaura navegação ao fechar.');

class MockVoice{constructor(){MockVoice.current=this;}start(){this.onstart?.()}stop(){this.onend?.()}abort(){this.aborted=true;this.onend?.()}}
t.voice.Recognition=MockVoice;t.go('chat');t.clearFlows();map.get('chatText').value='';const beforeVoiceEntries=JSON.stringify(t.get().state.entries),beforeVoiceMessages=t.get().messages.length;t.openVoice();assert.equal(map.get('voiceDialog').open,true);assert.equal(map.get('voiceText').readOnly,true);MockVoice.current.onresult({results:[[{transcript:'Gastei 30,00 reais com sementes'}]]});assert.ok(map.get('voiceText').value.includes('30,00'));assert.equal(t.get().messages.length,beforeVoiceMessages);assert.equal(JSON.stringify(t.get().state.entries),beforeVoiceEntries);await map.get('voiceConfirm').onclick();assert.equal(t.get().messages.length,beforeVoiceMessages,'não confirma enquanto está ouvindo');map.get('voiceStop').onclick();assert.equal(map.get('voiceText').readOnly,false);map.get('voiceText').value='Gastei 35,00 reais com sementes';await map.get('voiceConfirm').onclick();assert.equal(map.get('voiceDialog').open,false);assert.equal(t.get().draft.cents,3500);assert.equal(JSON.stringify(t.get().state.entries),beforeVoiceEntries,'confirmação de voz envia texto, não salva despesa automaticamente');const beforeCancel=t.get().messages.length;t.openVoice();MockVoice.current.onresult({results:[[{transcript:'Teste descartado'}]]});map.get('voiceCancel').onclick();assert.equal(t.get().messages.length,beforeCancel);assert.ok(MockVoice.current.aborted);console.log('OK: microfone, texto reconhecido, edição antes de confirmar, envio explícito e cancelamento sem alterar lançamentos.');
