import {test} from 'node:test';import assert from 'node:assert/strict';
import {assertPermission,permissionsOf,fullPermissions,readPermissions,validatePermissions} from '../permissions.js';import {manageUsers} from '../users.js';
const owner={id:'owner',space:'space-a',isOwner:true},id='00000000-0000-4000-8000-000000000099';
function fixture(){const rows=[{id:'owner',space_id:'space-a',username:'owner',display_name:'Dono',active:true,is_owner:true,permissions:fullPermissions(),access_version:1,password_hash:'secret',password_salt:'secret-salt'},{id,space_id:'space-a',username:'yasmin.financeiro',display_name:'Yasmin',active:true,is_owner:false,permissions:fullPermissions(),access_version:1,password_hash:'secret',password_salt:'secret-salt'},{id:'00000000-0000-4000-8000-000000000098',space_id:'space-b',username:'other',display_name:'Outro',active:true,is_owner:false,permissions:fullPermissions(),access_version:1}];let deletes=[];const db=async(table,q,method='GET',body)=>{if(table==='lt_pf_tokens_internal'){deletes.push(q);return [];}const params=new URLSearchParams(q.slice(1));let found=rows.filter(r=>[...params].every(([k,v])=>!v.startsWith('eq.')||String(r[k])===v.slice(3)));if(method==='POST'){rows.push(structuredClone(body));return [structuredClone(body)];}if(method==='PATCH'){found.forEach(r=>Object.assign(r,body));}return structuredClone(found);};return {rows,deletes,db,passwordHash:async(p,s)=>'HASH:'+p+':'+s};}
const update=()=>({action:'userUpdate',id,name:'Yasmin',active:true,version:1,permissions:readPermissions()});
test('consulta permite perguntas mas bloqueia cada mutação e usuários; proprietário não libera ação desconhecida',()=>{const reader={permissions:readPermissions()};for(const a of ['state','chatState','chatAppend','ensureInvoices'])assert.doesNotThrow(()=>assertPermission(reader,a));for(const a of ['entry','deleteEntry','restoreEntry','settleEntry','account','card','invoiceCheck','invoiceClose','invoicePay','invoiceReopen','invoiceUndoPay','invoiceSnooze','budget','budgetSettings','budgetResponse','usersList','userCreate','userUpdate'])assert.throws(()=>assertPermission(reader,a),e=>e.status===403);assert.throws(()=>assertPermission(owner,'anything'),e=>e.status===403);assert.deepEqual(permissionsOf(owner),fullPermissions());});
test('cada grupo permite somente suas próprias alterações e acesso sem consulta não lê conversas',()=>{for(const [key,action] of Object.entries({entries:'entry',invoices:'invoicePay',accounts:'account',cards:'card',budgets:'budget'})){const user={permissions:{...readPermissions(),[key]:true}};assert.doesNotThrow(()=>assertPermission(user,action));}assert.throws(()=>assertPermission({permissions:{}},'chatState'));assert.throws(()=>validatePermissions({...readPermissions(),view:false,entries:true}));assert.throws(()=>validatePermissions({...readPermissions(),owner:true}));});
test('cadastro fixa financeiro e membro, guarda somente hash e lista sem segredos',async()=>{const f=fixture();const created=await manageUsers(owner,{action:'userCreate',id:'00000000-0000-4000-8000-000000000097',name:'Novo',username:'novo.financeiro',password:'Nova.12345',permissions:readPermissions() },f);const row=f.rows.at(-1);assert.equal(row.space_id,'space-a');assert.equal(row.is_owner,false);assert.notEqual(row.password_hash,'Nova.12345');assert.equal(created.user.password_hash,undefined);const list=await manageUsers(owner,{action:'usersList'},f);assert.equal(list.users.length,3);assert.ok(!JSON.stringify(list).includes('secret'));assert.ok(!list.users.some(u=>u.username==='other'));});
test('outro usuário não gerencia acessos e proprietário não altera usuário de outro financeiro',async()=>{const f=fixture();await assert.rejects(manageUsers({space:'space-a',permissions:fullPermissions()},update(),f),e=>e.status===403);await assert.rejects(manageUsers(owner,{...update(),id:'00000000-0000-4000-8000-000000000098'},f),e=>e.status===404);assert.equal(f.rows[2].access_version,1);});
test('proprietário é protegido, promoção e mudança de financeiro são rejeitadas',async()=>{const f=fixture();f.rows[0].id='00000000-0000-4000-8000-000000000096';await assert.rejects(manageUsers(owner,{...update(),id:f.rows[0].id},f),e=>e.status===403);for(const extra of [{isOwner:true},{space_id:'space-b'},{space:'space-b'}])await assert.rejects(manageUsers(owner,{...update(),...extra},f),e=>e.status===403);});
test('permissões mudam com comparação de versão, sem alterar senha nem lançar dados financeiros',async()=>{const f=fixture();const saved=await manageUsers(owner,update(),f);assert.deepEqual(saved.user.permissions,readPermissions());assert.equal(f.rows[1].password_hash,'secret');assert.equal(saved.user.version,2);await assert.rejects(manageUsers(owner,update(),f),e=>e.status===409);assert.equal(f.deletes.length,0);});
test('desativação e troca de senha revogam sessões; duplicação e senhas fracas são bloqueadas',async()=>{const f=fixture();await manageUsers(owner,{...update(),active:false},f);assert.equal(f.deletes.length,1);await manageUsers(owner,{...update(),version:2,password:'Outra.12345'},f);assert.equal(f.deletes.length,2);await assert.rejects(manageUsers(owner,{action:'userCreate',id:'00000000-0000-4000-8000-000000000097',name:'Novo',username:'yasmin.financeiro',password:'Forte.12345',permissions:readPermissions()},f),e=>e.status===409);await assert.rejects(manageUsers(owner,{...update(),version:3,password:'123'},f),/8 a 100/);});
