import {summarize} from './ledger.js';
import {parseMessage,normalize,moneyCents,categories,categoryOf,shiftDate} from './conversation.js';
const endpoint='https://wwietlvweqsxfpejhhis.supabase.co/functions/v1/lt-meu-financeiro',publicKey='sb_publishable_dArUUh2qpDqbzvjxXAEbNQ_hT6Y0y5y';
const authKey='lt_pf_luciano_yasmin_auth_v1',$=id=>document.getElementById(id);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>(n/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo'}).format(new Date()),formatDate=s=>s?s.split('-').reverse().join('/'):'—';
let auth=null,state={accounts:[],entries:[]},user=null,tab='chat',messages=[],draft=null,editing=null,accountEditing=null,busy=false,refreshing=null,queryTimer=null,accountScope='all',entryFilter='all',month=today().slice(0,7),search='',deletedView=false;
try{auth=JSON.parse(localStorage.getItem(authKey)||'null')}catch{}
const chatKey=()=> 'lt_pf_ly_chat_'+user.id;
function maskedMoney(raw){const digits=String(raw).replace(/\D/g,'');if(!digits)return '';const cents=Number(digits);if(!Number.isSafeInteger(cents))return raw;const negative=String(raw).includes('-');return (negative?'-':'')+money(cents);}
function bindMoneyInput(input){
 input.addEventListener('input',()=>{input.value=maskedMoney(input.value);});
 input.addEventListener('focus',()=>input.select());
 input.addEventListener('paste',event=>{const raw=event.clipboardData?.getData('text');const cents=moneyCents(raw);if(cents!==null){event.preventDefault();input.value=money(cents);}});
}
[$('entryAmount'),$('accountBalance')].forEach(bindMoneyInput);

function toast(text){$('toast').textContent=text;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,4000)}
function connection(text,bad=false){$('connection').textContent=text;$('connection').classList.toggle('bad',bad)}
async function api(body){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);try{const r=await fetch(endpoint,{method:'POST',headers:{apikey:publicKey,'Content-Type':'application/json',...(auth?.token?{Authorization:'Bearer '+auth.token}:{})},body:JSON.stringify(body),signal:controller.signal,cache:'no-store'});let result;try{result=await r.json()}catch{throw Error('Resposta indisponível. Tente novamente.')}if(!r.ok){const e=Object.assign(Error(result.message||'Não foi possível concluir.'),{status:r.status});if(r.status===401&&body.action!=='login'){localStorage.removeItem(authKey);auth=null;$('shell').hidden=true;$('loginScreen').hidden=false;$('loginError').textContent='Entre novamente para continuar.'}throw e}return result}catch(e){if(e.name==='AbortError'||e instanceof TypeError)throw Error('Sem resposta do servidor. Confira a internet e tente novamente.');throw e}finally{clearTimeout(timer)}}
async function refresh(renderView=true){if(!auth)return;if(refreshing)return refreshing;refreshing=(async()=>{try{const result=await api({action:'state'});const previous=JSON.stringify(state);state=result.data;user=result.user;$('who').textContent=user.name;$('shell').hidden=false;$('loginScreen').hidden=true;connection('Compartilhado entre Luciano e Yasmin · Atualizado');if(!messages.length){try{const saved=JSON.parse(localStorage.getItem(chatKey())||'[]');messages=Array.isArray(saved)?saved:[]}catch{}if(!messages.length)addMessage('bot','Olá, '+user.name+'! Conte uma receita ou despesa. Vou pedir o que faltar e você confirma antes de salvar.')}if(renderView||previous!==JSON.stringify(state))render()}catch(e){connection(e.message,true);if($('shell').hidden)$('loginError').textContent=e.message;throw e}finally{refreshing=null}})();return refreshing}
function addMessage(role,text){messages.push({role,text,time:new Date().toISOString()});messages=messages.slice(-100);if(user)try{localStorage.setItem(chatKey(),JSON.stringify(messages))}catch{}}
function accountName(id){return state.accounts.find(a=>a.id===id)?.name||'Conta'}
function scopeLabel(scope){return {casal:'Do casal',luciano:'Luciano',yasmin:'Yasmin'}[scope]||scope}
function entryAmount(e){return '<span class="amount '+(e.kind==='expense'?'red':'green')+'">'+(e.kind==='expense'?'−':'+')+money(e.cents)+'</span>'}
function go(next){tab=next;render();window.scrollTo({top:0,behavior:'smooth'})}
function render(){if(!user)return;const input=$('chatText'),typed=input?.value,focused=input===document.activeElement,pos=input?.selectionStart;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('content').innerHTML=tab==='chat'?chatView():tab==='summary'?summaryView():tab==='entries'?entriesView():accountsView();bindView();if(typed&&$('chatText')){$('chatText').value=typed;if(focused){$('chatText').focus();$('chatText').setSelectionRange(pos,pos)}}}
function chatView(){return '<div class="chat-layout"><div class="chat-intro"><h2>Vamos organizar seu dinheiro?</h2><p>Escreva do seu jeito. Confira os dados antes de confirmar.</p></div><div class="chat-chips"><button data-example="Gastei 50 reais no mercado hoje">Registrar uma despesa</button><button data-example="Recebi 100 reais hoje">Registrar uma entrada</button><button data-example="Qual meu saldo?">Ver meu saldo</button></div>'+(!state.accounts.length?'<div class="card"><h3>Primeiro, adicione uma conta</h3><p class="muted">Pode ser seu banco, carteira ou dinheiro em casa. Informe também o saldo inicial.</p><button data-add-account>Adicionar minha primeira conta</button></div>':'')+'<div class="chat-stream">'+messages.map(m=>'<div class="bubble '+(m.role==='me'?'me':'')+'"><small>'+escape(m.role==='me'?user.name:'Meu Financeiro')+'</small>'+escape(m.text)+'</div>').join('')+(draft?draftBubble():'')+'</div><form id="chatForm" class="chat-compose"><textarea id="chatText" rows="1" aria-label="Sua mensagem" placeholder="Ex.: Paguei 85 reais de mercado…" maxlength="700"></textarea><button type="submit" aria-label="Enviar mensagem">↑</button></form><p class="chat-footnote">Texto nesta versão · Nenhum lançamento é salvo sem confirmar.</p></div>'}
function draftBubble(){const complete=draft.kind&&draft.cents&&draft.status&&draft.accountId&&!draft.invalidDate;return '<div class="bubble"><small>'+escape(complete?'Pronto para conferir':'Lançamento em preparação')+'</small><b>'+escape(draft.description||'Novo lançamento')+'</b>'+(draft.cents?'<div class="preview-value">'+money(draft.cents)+'</div>':'')+(complete?'<div>'+escape(draft.kind==='income'?'Entrada':'Saída')+' · '+escape(accountName(draft.accountId))+'<br>'+escape(draft.status==='paid'?'Pago / recebido':'Pendente')+' · '+formatDate(draft.dueDate||draft.date)+'<br>'+escape(draft.category)+' · '+scopeLabel(draft.scope)+'</div><button id="reviewDraft">Conferir e confirmar</button>':'<p class="muted">'+escape(missingPrompt())+'</p>')+'<button id="discardDraft" class="secondary">Cancelar este lançamento</button></div>'}
function missingPrompt(){if(!draft.kind)return 'É uma entrada ou uma despesa?';if(!draft.cents)return 'Qual foi o valor? Ex.: 85,50';if(draft.invalidDate)return 'Qual é a data correta? Ex.: 06/10/2026';if(!draft.status)return draft.kind==='income'?'Já recebeu ou ainda está para receber?':'Já pagou ou ainda está para pagar?';if(!draft.accountId)return 'Em qual conta? '+state.accounts.filter(a=>!a.deleted).map(a=>a.name).join(', ')+'.';return 'Confira os dados antes de salvar.'}
function replyQuery(text){const n=normalize(text),monthNow=today().slice(0,7),s=summarize(state,monthNow);if(/\b(saldo|quanto tenho|quanto temos)\b/.test(n))return 'Saldo disponível nas contas: '+money(s.balance)+'.\nContas a pagar neste mês: '+money(s.payable)+'.\nValores a receber neste mês: '+money(s.receivable)+'.\nSó valores pagos/recebidos entram no saldo.';
 if(/quanto.*(gastei|gastamos|recebi|recebemos|entrou)/.test(n)){const income=/recebi|recebemos|entrou/.test(n),cat=categoryOf(n),sum=state.entries.filter(e=>!e.deleted&&e.status==='paid'&&e.kind===(income?'income':'expense')&&e.paidDate.startsWith(monthNow)&&(cat==='Outros'||e.category===cat)).reduce((v,e)=>v+e.cents,0);return (income?'Entradas recebidas':'Despesas pagas')+(cat==='Outros'?'':' em '+cat.toLowerCase())+' neste mês: '+money(sum)+'.'}
 if(/\b(contas|o que|quanto)\b.*\b(pagar|receber|vence|vencem|vencimento)\b/.test(n)){let from=today(),to=shiftDate(from,7);if(n.includes('amanha'))from=to=shiftDate(from,1);else if(n.includes('hoje'))to=from;const income=n.includes('receber'),list=state.entries.filter(e=>!e.deleted&&e.status==='pending'&&e.kind===(income?'income':'expense')&&e.dueDate>=from&&e.dueDate<=to).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));return list.length?'De '+formatDate(from)+' a '+formatDate(to)+':\n'+list.map(e=>formatDate(e.dueDate)+' · '+e.description+' · '+money(e.cents)).join('\n'):'Nenhuma conta '+(income?'a receber':'a pagar')+' nesse período.';}return null;}
function sendMessage(text){text=text.trim();if(!text)return;if($('chatText'))$('chatText').value='';addMessage('me',text);const normalized=normalize(text);if(normalized==='cancelar'||normalized==='cancela'){draft=null;addMessage('bot','Lançamento descartado. Nada foi salvo.');render();return}if(!draft){const answer=replyQuery(text);if(answer){addMessage('bot',answer);render();return}if(!state.accounts.length){addMessage('bot','Adicione uma conta primeiro. Assim posso registrar de onde o dinheiro saiu ou onde entrou.');render();return}}
 const parsed=parseMessage(text,state.accounts.filter(a=>!a.deleted),today());
 if(!draft)draft={id:crypto.randomUUID(),description:text.slice(0,300),date:today(),dueDate:today(),scope:'casal',category:parsed.category};
 if(!draft.kind&&/^(entrada|receita)$/.test(normalized))parsed.kind='income';if(!draft.kind&&/^(saida|despesa)$/.test(normalized))parsed.kind='expense';
 if(!draft.cents&&!parsed.cents){const value=moneyCents(text);if(value>0)parsed.cents=value}
 if(!draft.status&&/^(sim|ja|ja sim)$/.test(normalized))parsed.status='paid';if(!draft.status&&/^(nao|ainda nao)$/.test(normalized))parsed.status='pending';
 if(!draft.kind&&parsed.kind)draft.kind=parsed.kind;for(const k of ['cents','accountId','status','date','dueDate','scope'])if(parsed[k]!==undefined&&parsed[k]!==null)draft[k]=parsed[k];
 if(parsed.invalidDate)draft.invalidDate=true;else if(parsed.date)draft.invalidDate=false;
 if(parsed.category!=='Outros')draft.category=parsed.category;
 const complete=draft.kind&&draft.cents&&draft.accountId&&draft.status&&!draft.invalidDate;
 addMessage('bot',complete?'Entendi. Toque em “Conferir e confirmar” para revisar todos os dados.':missingPrompt());render();$('chatText').focus();document.querySelector('.chat-compose').scrollIntoView({block:'end',behavior:'smooth'});
}
function summaryView(){const s=summarize(state,month),entries=state.entries.filter(e=>!e.deleted&&e.status==='paid'&&e.kind==='expense'&&e.paidDate.startsWith(month)),group={};for(const e of entries)group[e.category]=(group[e.category]||0)+e.cents;return '<div class="page-head"><div><h2>Seu dinheiro, com clareza</h2><p class="muted">Resumo compartilhado do casal</p></div><input id="summaryMonth" type="month" value="'+month+'" aria-label="Mês do resumo" style="max-width:170px"></div><div class="kpis"><div class="kpi main"><small>SALDO DISPONÍVEL · TODAS AS CONTAS</small><strong>'+money(s.balance)+'</strong><span>Saldo inicial + entradas recebidas − despesas pagas</span></div>'+[['Entradas recebidas',s.income,'green'],['Despesas pagas',s.expense,'red'],['A pagar no mês',s.payable,''],['A receber no mês',s.receivable,'']].map(([label,value,cls])=>'<div class="kpi"><small>'+label+'</small><strong class="'+cls+'">'+money(value)+'</strong></div>').join('')+'</div><div class="card"><h3>Onde está o dinheiro</h3>'+(s.accounts.length?s.accounts.map(a=>'<div class="row"><div><strong>'+escape(a.name)+'</strong></div><div class="amount">'+money(a.balance)+'</div></div>').join(''):'<p class="muted">Adicione suas contas e seus saldos iniciais para começar.</p><button data-add-account>Adicionar conta</button>')+'</div><div class="card mini-bars"><h3>Despesas pagas por categoria</h3>'+(Object.keys(group).length?Object.entries(group).sort((a,b)=>b[1]-a[1]).map(([cat,value])=>'<div class="row"><div class="bar-label"><span>'+escape(cat)+'</span><b>'+money(value)+'</b></div><div class="bar" style="width:'+Math.max(3,value/Math.max(s.expense,1)*100)+'%"></div></div>').join(''):'<p class="muted">Os gastos aparecem aqui conforme vocês confirmarem os lançamentos.</p>')+'</div>'}
function entriesView(){let list=state.entries.filter(e=>!!e.deleted===deletedView&&(entryFilter==='all'||e.status===entryFilter)&&(accountScope==='all'||e.scope===accountScope)&&(e.status==='paid'?e.paidDate:e.dueDate).startsWith(month)&&normalize(e.description+' '+e.category+' '+e.createdBy).includes(normalize(search))).sort((a,b)=>(b.date+b.createdAt).localeCompare(a.date+a.createdAt));return '<div class="page-head"><div><h2>'+ (deletedView?'Lixeira':'Lançamentos')+'</h2><p class="muted">Cada movimentação, com quem registrou</p></div><button id="newEntry">+ Lançamento</button></div><div class="filters"><input id="entriesMonth" type="month" value="'+month+'" aria-label="Mês dos lançamentos"><select id="entryFilter" aria-label="Situação"><option value="all">Todas as situações</option><option value="paid" '+(entryFilter==='paid'?'selected':'')+'>Pagos / recebidos</option><option value="pending" '+(entryFilter==='pending'?'selected':'')+'>Pendentes</option></select><select id="scopeFilter" aria-label="Pessoa">'+[['all','Todos'],['casal','Do casal'],['luciano','Luciano'],['yasmin','Yasmin']].map(([v,label])=>'<option value="'+v+'" '+(accountScope===v?'selected':'')+'>'+label+'</option>').join('')+'</select><input class="search" id="entrySearch" placeholder="Buscar descrição, categoria ou pessoa" value="'+escape(search)+'"><button id="toggleTrash" class="secondary">'+(deletedView?'Voltar aos lançamentos':'Ver lixeira')+'</button></div>'+(list.length?'<div class="entries-list">'+list.map(e=>'<div class="card entry-card"><div class="entry-header"><h3>'+escape(e.description)+'</h3>'+entryAmount(e)+'</div><div class="entry-info"><span class="badge '+(e.status==='pending'?'pending':'')+'">'+(e.status==='pending'?(e.kind==='expense'?'A pagar':'A receber'):(e.kind==='expense'?'Pago':'Recebido'))+'</span> '+escape(accountName(e.accountId))+' · '+escape(e.category)+'<br>'+scopeLabel(e.scope)+' · '+(e.status==='paid'?'Pagamento: '+formatDate(e.paidDate):'Vencimento: '+formatDate(e.dueDate))+'<br>Registrado por '+escape(e.createdBy)+(e.updatedBy!==e.createdBy?' · Editado por '+escape(e.updatedBy):'')+'</div><div class="row-actions">'+(deletedView?'<button class="secondary" data-restore="'+e.id+'">Restaurar</button>':'<button class="secondary" data-edit="'+e.id+'">Editar</button>'+(e.status==='pending'?'<button data-settle="'+e.id+'">'+(e.kind==='income'?'Marcar recebido':'Marcar pago')+'</button>':'')+'<button class="danger" data-delete="'+e.id+'">Apagar</button>')+'</div></div>').join('')+'</div>':'<div class="card empty"><span class="empty-icon">⇅</span><h3>Nenhum lançamento neste filtro</h3><p class="muted">Você pode registrar pela conversa ou usar o botão “+ Lançamento”.</p></div>')}
function accountsView(){const s=summarize(state,month);return '<div class="page-head"><div><h2>Suas contas</h2><p class="muted">Contas compartilhadas, saldos organizados</p></div><button data-add-account>+ Conta</button></div>'+(s.accounts.length?'<div class="accounts-grid">'+s.accounts.map(a=>'<div class="card"><div class="entry-header"><h3>'+escape(a.name)+'</h3><button class="text-button" data-edit-account="'+a.id+'">Editar</button></div><p class="muted">Saldo disponível</p><div class="metric '+(a.balance<0?'red':'green')+'" style="font-size:28px;font-weight:750">'+money(a.balance)+'</div><p class="muted">Saldo inicial: '+money(a.openingCents)+'</p></div>').join('')+'</div>':'<div class="card empty"><span class="empty-icon">▱</span><h3>Comece pela primeira conta</h3><p class="muted">Cadastre seu banco ou carteira e o saldo antes dos novos lançamentos.</p><button data-add-account>Adicionar conta</button></div>')+'<div class="card"><h3>Compartilhado com</h3><div class="row"><strong>Luciano</strong><span class="badge">Pode registrar e editar</span></div><div class="row"><strong>Yasmin</strong><span class="badge">Pode registrar e editar</span></div><p class="muted" style="margin-top:15px">Somente os acessos deste espaço consultam estes dados. “Pessoal” organiza os lançamentos; ambos continuam podendo vê-los.</p><div class="install-help"><span class="muted">Use como aplicativo no celular.</span><button id="install" class="secondary">Instalar app</button></div></div>'}
function bindView(){document.querySelectorAll('[data-add-account]').forEach(b=>b.onclick=()=>openAccount());document.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>{$('chatText').value=b.dataset.example;$('chatText').focus()});if($('chatForm')){$('chatForm').onsubmit=e=>{e.preventDefault();sendMessage($('chatText').value)};$('chatText').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage($('chatText').value)}}}if($('reviewDraft'))$('reviewDraft').onclick=()=>openEntry(draft,true);if($('discardDraft'))$('discardDraft').onclick=()=>{draft=null;addMessage('bot','Lançamento descartado. Nada foi salvo.');render()};if($('summaryMonth'))$('summaryMonth').onchange=e=>{if(e.target.value){month=e.target.value;render()}};if($('entriesMonth'))$('entriesMonth').onchange=e=>{if(e.target.value){month=e.target.value;render()}};if($('entryFilter'))$('entryFilter').onchange=e=>{entryFilter=e.target.value;render()};if($('scopeFilter'))$('scopeFilter').onchange=e=>{accountScope=e.target.value;render()};if($('entrySearch'))$('entrySearch').oninput=e=>{search=e.target.value;clearTimeout(queryTimer);queryTimer=setTimeout(()=>{const pos=$('entrySearch').selectionStart;render();$('entrySearch').focus();$('entrySearch').setSelectionRange(pos,pos)},350)};if($('toggleTrash'))$('toggleTrash').onclick=()=>{deletedView=!deletedView;render()};if($('newEntry'))$('newEntry').onclick=()=>openEntry();document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEntry(state.entries.find(e=>e.id===b.dataset.edit)));document.querySelectorAll('[data-edit-account]').forEach(b=>b.onclick=()=>openAccount(state.accounts.find(a=>a.id===b.dataset.editAccount)));for(const [attr,action] of [['delete','deleteEntry'],['restore','restoreEntry'],['settle','settleEntry']])document.querySelectorAll('[data-'+attr+']').forEach(b=>b.onclick=()=>changeEntry(b.dataset[attr],action));if($('install'))$('install').onclick=installApp}
function openEntry(entry=null,fromDraft=false){if(!state.accounts.length){toast('Adicione uma conta primeiro.');openAccount();return}editing={id:entry?.id||crypto.randomUUID(),version:fromDraft?null:entry?.version,createOnly:fromDraft||!entry,fromDraft};$('editorTitle').textContent=editing.createOnly?'Confira o lançamento':'Editar lançamento';$('editorError').textContent='';$('entryKind').value=entry?.kind||'expense';$('entryAmount').value=entry?.cents?money(entry.cents):'';$('entryDescription').value=entry?.description||'';$('entryAccount').innerHTML=state.accounts.filter(a=>!a.deleted).map(a=>'<option value="'+a.id+'">'+escape(a.name)+'</option>').join('');if(entry?.accountId)$('entryAccount').value=entry.accountId;$('entryCategory').innerHTML=[...new Set([...categories,...(entry?.category?[entry.category]:[])])].map(c=>'<option>'+escape(c)+'</option>').join('');$('entryCategory').value=entry?.category||'Outros';$('entryScope').value=entry?.scope||'casal';$('entryStatus').value=entry?.status||'paid';$('entryDate').value=entry?.date||today();$('entryDue').value=entry?.dueDate||entry?.date||today();$('entryPaid').value=entry?.paidDate||entry?.date||today();updatePaidField();$('editor').showModal()}
function updatePaidField(){$('entryPaid').disabled=$('entryStatus').value==='pending';$('entryPaid').required=!$('entryPaid').disabled}
function openAccount(account=null){accountEditing=account||{id:crypto.randomUUID()};$('accountTitle').textContent=account?'Editar conta':'Adicionar conta';$('accountName').value=account?.name||'';$('accountBalance').value=money(account?.openingCents||0);$('accountError').textContent='';$('accountEditor').showModal()}
async function changeEntry(id,action){if(busy)return;const e=state.entries.find(e=>e.id===id);if(!e)return;const question=action==='deleteEntry'?'Mover este lançamento para a lixeira? Ele deixará de entrar nos saldos e poderá ser restaurado.':action==='restoreEntry'?'Restaurar este lançamento? Ele voltará a entrar nos saldos.':'Confirmar '+(e.kind==='income'?'recebimento':'pagamento')+' de '+money(e.cents)+' hoje na conta '+accountName(e.accountId)+'?';if(!confirm(question))return;busy=true;try{const result=await api({action,id,version:e.version,paidDate:today()});state=result.data;render();toast('Lançamento atualizado.')}catch(err){toast(err.message);await refresh().catch(()=>{})}finally{busy=false}}
$('editForm').onsubmit=async event=>{event.preventDefault();if(busy)return;const cents=moneyCents($('entryAmount').value);if(!cents||cents<0){$('editorError').textContent='Informe um valor maior que zero.';return}const entry={kind:$('entryKind').value,cents,description:$('entryDescription').value,accountId:$('entryAccount').value,category:$('entryCategory').value,scope:$('entryScope').value,status:$('entryStatus').value,date:$('entryDate').value,dueDate:$('entryDue').value,paidDate:$('entryPaid').value};busy=true;$('confirmEntry').disabled=true;$('editorError').textContent='';try{const result=await api({action:'entry',id:editing.id,version:editing.version,createOnly:editing.createOnly,entry});state=result.data;if(editing.fromDraft){addMessage('bot',(entry.kind==='income'?'Entrada':'Despesa')+' de '+money(entry.cents)+' registrada em '+accountName(entry.accountId)+', '+(entry.status==='paid'?'paga/recebida':'pendente')+'.');draft=null}$('editor').close();render();toast('Salvo no financeiro compartilhado.')}catch(e){$('editorError').textContent=e.message;if(e.status===409)await refresh(false).catch(()=>{})}finally{busy=false;$('confirmEntry').disabled=false}};
$('accountForm').onsubmit=async event=>{event.preventDefault();if(busy)return;const cents=moneyCents($('accountBalance').value);if(cents===null){$('accountError').textContent='Confira o saldo inicial.';return}busy=true;$('saveAccount').disabled=true;$('accountError').textContent='';try{const result=await api({action:'account',id:accountEditing.id,version:accountEditing.version,name:$('accountName').value,openingCents:cents});state=result.data;$('accountEditor').close();render();toast('Conta salva.')}catch(e){$('accountError').textContent=e.message}finally{busy=false;$('saveAccount').disabled=false}};
$('entryStatus').onchange=updatePaidField;$('closeEditor').onclick=()=>{if(!busy)$('editor').close()};$('closeAccount').onclick=()=>{if(!busy)$('accountEditor').close()};
for(const dialog of [$('editor'),$('accountEditor')])dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault()});
$('loginForm').onsubmit=async event=>{event.preventDefault();$('loginButton').disabled=true;$('loginError').textContent='';try{const result=await api({action:'login',username:$('username').value,password:$('password').value});localStorage.setItem(authKey,JSON.stringify(result));auth=result;$('password').value='';await refresh()}catch(e){$('loginError').textContent=e.message}finally{$('loginButton').disabled=false}};
$('refresh').onclick=()=>refresh().catch(()=>{});$('logout').onclick=async()=>{if(!confirm('Sair deste aparelho?'))return;const current=auth;try{await api({action:'logout'})}catch{}localStorage.removeItem(authKey);if(user)localStorage.removeItem(chatKey());auth=null;user=null;state={accounts:[],entries:[]};messages=[];draft=null;$('shell').hidden=true;$('loginScreen').hidden=false;$('loginError').textContent='';};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>go(b.dataset.tab));
let installPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});async function installApp(){if(installPrompt){await installPrompt.prompt();installPrompt=null}else alert('No iPhone: abra no Safari, toque em Compartilhar e “Adicionar à Tela de Início”. No Android: use o menu do navegador e “Instalar app” ou “Adicionar à tela inicial”. Faça login uma vez no aplicativo instalado.');}
window.addEventListener('focus',()=>{if(auth)refresh(false).catch(()=>{})});window.addEventListener('online',()=>{if(auth)refresh(false).catch(()=>{})});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&auth)refresh(false).catch(()=>{})});setInterval(()=>{if(auth&&!document.hidden&&!busy&& !$('editor').open&&!$('accountEditor').open)refresh(false).catch(()=>{})},20000);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'}).catch(()=>{});
if(auth){$('loginError').textContent='Abrindo seu financeiro…';refresh().catch(()=>{});}
