/* LT Soluções: dados exclusivos da demonstração. Não usa servidores de clientes. */
(function(root){
'use strict';
const dataKey='lt_demo_barbearia_data_v3',panelKey='lt_demo_barbearia_panel_v3';
const baseURL='https://barbearia-demo.invalid';
const copy=x=>JSON.parse(JSON.stringify(x));
function today(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function week(){const w={};for(let i=0;i<7;i++)w[i]={active:i>0,open:'09:00',lunchStart:'12:00',lunchEnd:'13:30',close:i===6?'16:00':'18:00'};return w}
function defaults(){return {version:3,nextId:1,bookings:[],series:[],hours:[{barber_id:1,weekly:week()},{barber_id:2,weekly:week()}],blocks:[],holidays:[],catalog:{business:{name:'Barbearia Demonstração',address:'',whatsapp:'',logo:''},services:[{id:1,name:'Corte',price:35,duration:30,active:true},{id:2,name:'Barba',price:25,duration:20,active:true},{id:3,name:'Corte + Barba',price:55,duration:50,active:true}],barbers:[{id:1,name:'Profissional 1',active:true,serviceIds:[1,2,3]},{id:2,name:'Profissional 2',active:true,serviceIds:[1,2,3]}]}}}
function read(){let data;try{data=JSON.parse(root.localStorage.getItem(dataKey)||'null')}catch(e){}return data&&data.version===3?data:defaults()}
function write(data){root.localStorage.setItem(dataKey,JSON.stringify(data))}
function response(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}})}
function minutes(t){const p=String(t).slice(0,5).split(':');return +p[0]*60+ +p[1]}
function formatDate(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function addMonths(value,n){const d=new Date(value+'T12:00:00'),day=d.getDate();d.setDate(1);d.setMonth(d.getMonth()+n);d.setDate(Math.min(day,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()));return formatDate(d)}
function dates(start,end,weekday){const out=[],d=new Date(start+'T12:00:00');for(let i=0;i<100&&formatDate(d)<=end;i++,d.setDate(d.getDate()+1))if(d.getDay()===+weekday)out.push(formatDate(d));return out}
function within(w,time,duration){const start=minutes(time),end=start+duration;return !!(w&&w.active&&w.open&&w.close&&duration>0&&start>=minutes(w.open)&&end<=minutes(w.close)&&end<1440&&!(w.lunchStart&&w.lunchEnd&&start<minutes(w.lunchEnd)&&end>minutes(w.lunchStart)))}
function schedule(data,bid,date,weekly){const h=data.holidays.find(h=>h.date===date),normal=weekly[new Date(date+'T12:00:00').getDay()];if(!h||!h.mode||h.mode==='normal')return normal;if(h.mode==='closed')return{active:false};if(h.mode==='special')return h.hours;if(h.mode==='barbers'&&h.byBarber&&h.byBarber[bid])return h.byBarber[bid];return normal}
function overlaps(data,b){const start=minutes(b.start_time),end=start+ +b.duration_minutes;return data.bookings.some(x=>x.barber_id==b.barber_id&&x.booking_date===b.booking_date&&['Agendado','Confirmado','Atendido'].includes(x.status)&&x.id!==b.id&&start<minutes(x.start_time)+ +x.duration_minutes&&end>minutes(x.start_time))}
function blocked(data,b){const start=minutes(b.start_time),end=start+ +b.duration_minutes;return data.blocks.some(x=>x.barberId==b.barber_id&&x.date===b.booking_date&&start<minutes(x.end)&&end>minutes(x.start))}
function createBooking(data,body){if(!body.booking_date||body.booking_date<today()||!body.client_name||!body.client_phone||!body.barber_id||!body.service_id||!(+body.duration_minutes>0)||!Number.isFinite(minutes(body.start_time)))return response({message:'Dados de agendamento inválidos.'},400);if(overlaps(data,body))return response({message:'no_overlapping_public_bookings'},409);const row={...copy(body),id:data.nextId++,payment_method:body.payment_method||null,created_at:new Date().toISOString(),recurring_id:body.recurring_id||null};data.bookings.push(row);return row}
function filters(rows,params){return rows.filter(row=>{for(const [key,rule] of params){if(['select','order','limit'].includes(key))continue;if(rule.startsWith('eq.')&&String(row[key])!==rule.slice(3))return false;if(rule.startsWith('gte.')&&String(row[key])<rule.slice(4))return false;if(rule.startsWith('in.(')&&!rule.slice(4,-1).split(',').includes(String(row[key])))return false}return true})}
function project(rows,select){if(!select||select==='*')return rows;return rows.map(row=>Object.fromEntries(select.split(',').map(k=>[k,row[k]])))}
function plan(data,p){const q=copy(p.p_request||{}),commit=!!p.p_commit,skip=!!p.p_skip_conflicts;const start=q.start_date,end=q.end_date,wd=+q.weekday,duration=+q.duration_minutes,bid=+q.barber_id;
if(!q.id||!/^\d{4}-\d{2}-\d{2}$/.test(start||'')||!/^\d{4}-\d{2}-\d{2}$/.test(end||'')||start<today()||end<start||end>addMonths(start,3)||!Number.isInteger(wd)||wd<0||wd>6||!q.client_name||!q.client_phone||!q.service_name||!q.barber_name||!bid||!q.service_id||duration<=0||duration>=1440||!Number.isFinite(minutes(q.start_time))||!(+q.price>=0))return response({message:'Dados inválidos. Escolha um período de até 3 meses.'},400);
const old=data.series.find(s=>s.id===q.id);if(old&&!old.active)return response({message:'Este cliente fixo foi encerrado. Cadastre uma nova reserva.'},400);if(old&&['barber_id','service_id','weekday','start_time','duration_minutes','client_name','client_phone'].some(k=>String(old[k]).slice(0,k==='start_time'?5:10000)!==String(q[k]).slice(0,k==='start_time'?5:10000)))return response({message:'Os dados da reserva fixa foram alterados. Abra novamente o cadastro.'},400);
const hours=data.hours.find(h=>h.barber_id===bid);if(!hours)return response({message:'Salve os horários do profissional antes de cadastrar o cliente fixo.'},400);
const available=[],conflicts=[],existing=[],bookings=[];
for(const date of dates(start,end,wd)){if(data.bookings.some(b=>b.recurring_id===q.id&&b.booking_date===date)){existing.push(date);continue}let reason;const w=(q.special_hours||{})[date]||schedule(data,bid,date,hours.weekly),candidate={barber_id:bid,booking_date:date,start_time:q.start_time,duration_minutes:duration};if(new Date(date+'T'+q.start_time+':00')<=new Date())reason='Horário já passou';else if((q.excluded_dates||[]).includes(date)||blocked(data,candidate))reason='Bloqueado ou sem atendimento no app';else if(!w||!w.active)reason='Sem atendimento neste dia';else if(!within(w,q.start_time,duration))reason='Fora do horário de atendimento ou intervalo de almoço';else if(overlaps(data,candidate))reason='Horário já reservado';if(reason)conflicts.push({date,reason});else available.push(date)}
if(!commit||conflicts.length&&!skip||!available.length&&!existing.length)return response({committed:false,available,conflicts,existing,bookings});
if(!old)data.series.push({id:q.id,client_name:q.client_name,client_phone:q.client_phone,barber_id:bid,barber_name:q.barber_name,service_id:+q.service_id,service_name:q.service_name,duration_minutes:duration,price:+q.price,weekday:wd,start_time:q.start_time,start_date:start,end_date:end,active:true,created_at:new Date().toISOString()});
for(const date of available){const row=createBooking(data,{barber_id:bid,service_id:+q.service_id,client_name:q.client_name,client_phone:q.client_phone,service_name:q.service_name,barber_name:q.barber_name,booking_date:date,start_time:q.start_time,duration_minutes:duration,price:+q.price,status:'Agendado',recurring_id:q.id});if(row instanceof Response)return row;bookings.push(row)}
if(old&&end>old.end_date)old.end_date=end;write(data);return response({committed:true,available,conflicts,existing,bookings,created:bookings.length,series_id:q.id})}
function route(input,options={}){const url=new root.URL(String(input),baseURL);if(url.origin!==baseURL)return response({message:'Esta demonstração não acessa dados externos.'},403);const data=read(),method=(options.method||'GET').toUpperCase(),path=url.pathname,params=url.searchParams,body=options.body?JSON.parse(options.body):{};
if(path==='/functions/v1/demo-notification')return response({ok:true,demo:true,sent:0});
if(path==='/rest/v1/barbershop_public_bookings'){
if(method==='GET'){let rows=filters(data.bookings,params).sort((a,b)=>(a.booking_date+a.start_time).localeCompare(b.booking_date+b.start_time));if(params.get('select')==='start_time,duration_minutes,status'){const day=(params.get('booking_date')||'').slice(3),bid=(params.get('barber_id')||'').slice(3);rows=rows.concat(data.blocks.filter(b=>b.date===day&&b.barberId==bid).map(b=>({start_time:b.start,duration_minutes:minutes(b.end)-minutes(b.start),status:'Confirmado'})))}return response(project(rows,params.get('select')))}
if(method==='POST'){const row=createBooking(data,body);if(row instanceof Response)return row;write(data);return response([row],201)}
if(method==='PATCH'){const rows=filters(data.bookings,params);for(const row of rows){const next={...row,...body};if(['Agendado','Confirmado','Atendido'].includes(next.status)&&overlaps(data,next))return response({message:'no_overlapping_public_bookings'},409);Object.assign(row,body)}write(data);return response(rows)}
}
if(path==='/rest/v1/barbershop_public_hours'){if(method==='GET')return response(project(filters(data.hours.map(h=>({...h,catalog:h.catalog||{version:1,barber:(()=>{const b=data.catalog.barbers.find(b=>b.id==h.barber_id);return b?{id:b.id,name:b.name,active:b.active}:{id:h.barber_id,name:'Profissional',active:false}})(),services:data.catalog.services.map(s=>{const b=data.catalog.barbers.find(b=>b.id==h.barber_id),value=b&&b.servicePrices&&b.servicePrices[String(s.id)];return {...s,price:value!==undefined&&value!==null&&value!==''?+value:+s.price,active:!!(s.active&&b&&b.active&&(b.serviceIds||[]).some(id=>id==s.id))}})}})),params),params.get('select')));if(method==='PATCH'){const rows=filters(data.hours,params);for(const row of rows){if(body.weekly)row.weekly=copy(body.weekly);if(body.catalog)row.catalog=copy(body.catalog);}write(data);return response(rows)}if(method==='POST'){if(data.hours.some(h=>h.barber_id==body.barber_id))return response({message:'Profissional já cadastrado.'},409);data.hours.push(copy(body));write(data);return response([body],201)}}
if(path==='/rest/v1/barbershop_recurring_clients'&&method==='GET')return response(data.series.sort((a,b)=>Number(b.active)-Number(a.active)||a.end_date.localeCompare(b.end_date)));
if(path==='/rest/v1/rpc/barbershop_recurring_plan'&&method==='POST')return plan(data,body);
if(path==='/rest/v1/rpc/barbershop_recurring_end'&&method==='POST'){if(!String(body.p_reason||'').trim())return response({message:'Informe o motivo.'},400);const series=data.series.find(s=>s.id===body.p_id);if(!series)return response({message:'Cliente fixo não encontrado.'},404);series.active=false;let cancelled=0;for(const b of data.bookings)if(b.recurring_id===series.id&&new Date(b.booking_date+'T'+b.start_time.slice(0,5)+':00')>=new Date()&&['Agendado','Confirmado'].includes(b.status)){b.status='Cancelado';b.cancellation_reason=body.p_reason;cancelled++}write(data);return response({ok:true,cancelled})}
return response({message:'Ação não disponível na demonstração.'},404)}
let queue=Promise.resolve();function demoFetch(input,options){const run=()=>{try{return route(input,options)}catch(e){return response({message:'Não foi possível salvar os dados de teste: '+e.message},500)}};if(root.navigator&&root.navigator.locks)return root.navigator.locks.request(dataKey,run);const result=queue.then(run);queue=result.catch(()=>{});return result}
function updateCatalog(db){const data=read();data.catalog={business:copy(db.business),services:copy(db.services),barbers:copy(db.barbers)};data.blocks=copy(db.blocks||[]);data.holidays=copy(db.holidays||[]);for(const b of db.barbers)if(!data.hours.some(h=>h.barber_id==b.id))data.hours.push({barber_id:b.id,weekly:copy(b.weekly||week())});write(data)}
function populate(){const data=read(),s=document.getElementById('service'),b=document.getElementById('barber');if(!s||!b)return;function fill(){const sid=+s.value.split('|')[0];b.replaceChildren();for(const row of data.catalog.barbers.filter(b=>b.active&&(b.serviceIds||[]).includes(sid))){const option=document.createElement('option');option.value=row.id+'|'+row.name;option.textContent=row.name;b.appendChild(option)}}s.replaceChildren();for(const row of data.catalog.services.filter(s=>s.active)){const option=document.createElement('option');option.value=[row.id,row.name,row.price,row.duration].join('|');option.textContent=row.name+' · R$ '+Number(row.price).toFixed(2).replace('.',',')+' · '+row.duration+' min';s.appendChild(option)}fill();s.addEventListener('change',fill);const title=document.getElementById('demoBusinessName');if(title)title.textContent=data.catalog.business.name}
function reset(){if(!root.confirm('Limpar somente os dados de teste desta demonstração neste navegador?'))return;for(const key of [dataKey,panelKey,panelKey+'_hours_online_v1'])root.localStorage.removeItem(key);root.location.reload()}
root.BarberDemo=Object.freeze({baseURL,panelKey,fetch:demoFetch,today,updateCatalog,populateBookingForm:populate,schedule:(bid,date,weekly)=>schedule(read(),bid,date,weekly),reset});
})(window);

