import webpush from 'npm:web-push@3.6.7';
const api=Deno.env.get('SUPABASE_URL')+'/rest/v1/',key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const headers={apikey:key,Authorization:'Bearer '+key,'Content-Type':'application/json',Prefer:'return=representation'};
async function db(table:string,query='',method='GET',body?:unknown,ignore=false,merge=false){const r=await fetch(api+table+query,{method,headers:{...headers,Prefer:ignore?'resolution=ignore-duplicates,return=representation':merge?'resolution=merge-duplicates,return=representation':'return=representation'},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok)throw Error('Não foi possível configurar os avisos da estética.');return r.json()}
async function config(){let rows=await db('lt_yasmin_studio_push_config_internal','?id=eq.1');if(!rows.length){const keys=webpush.generateVAPIDKeys();await db('lt_yasmin_studio_push_config_internal','?on_conflict=id','POST',{id:1,vapid_public:keys.publicKey,vapid_private:keys.privateKey},true);rows=await db('lt_yasmin_studio_push_config_internal','?id=eq.1')}return rows[0]}
export function validSubscription(s:any){try{const u=new URL(s?.endpoint);return u.protocol==='https:'&&!u.username&&!u.password&&(!u.port||u.port==='443')&&(u.hostname==='fcm.googleapis.com'||u.hostname==='updates.push.services.mozilla.com'||u.hostname.endsWith('.push.apple.com')||u.hostname.endsWith('.notify.windows.com'))&&s.endpoint.length<2048&&/^[A-Za-z0-9_-]{86,88}$/.test(s.keys?.p256dh||'')&&/^[A-Za-z0-9_-]{22,24}$/.test(s.keys?.auth||'')}catch{return false}}
async function send(session:string,payload:any,onlyEndpoint?:string){const cfg=await config();webpush.setVapidDetails('https://luciaano68-art.github.io/lt-solucoes/clientes/yasmin-masson/',cfg.vapid_public,cfg.vapid_private);const rows=await db('lt_yasmin_studio_push_subscriptions_internal','?session_id=eq.'+session+(onlyEndpoint?'&endpoint=eq.'+encodeURIComponent(onlyEndpoint):''));let sent=0,failed=0;await Promise.all(rows.map(async(row:any)=>{try{await webpush.sendNotification(row.subscription,JSON.stringify(payload),{TTL:600,urgency:'high',timeout:10000});sent++}catch(e){failed++;if(e.statusCode===404||e.statusCode===410)await db('lt_yasmin_studio_push_subscriptions_internal','?session_id=eq.'+session+'&endpoint=eq.'+encodeURIComponent(row.endpoint),'DELETE')}}));return {attempted:rows.length,sent,failed}}
export async function pushAction(p:any,reply:any){
 if(p.action==='pushPublicKey')return reply({publicKey:(await config()).vapid_public});
 if(p.action==='pushSubscribe'){if(!validSubscription(p.subscription))return reply({message:'Inscrição de notificação inválida.'},400);const s={endpoint:p.subscription.endpoint,keys:{p256dh:p.subscription.keys.p256dh,auth:p.subscription.keys.auth}};await db('lt_yasmin_studio_push_subscriptions_internal','?on_conflict=endpoint','POST',{endpoint:s.endpoint,session_id:p.session,subscription:s,updated_at:new Date().toISOString()},false,true);return reply({ok:true})}
 if(p.action==='pushTest'){if(!validSubscription(p.subscription))return reply({message:'Ative as notificações neste aparelho primeiro.'},400);const result=await send(p.session,{title:'Teste — Yasmin Masson',body:'Os avisos de novos agendamentos estão ativados.',tag:'demo-push-test',url:'https://luciaano68-art.github.io/lt-solucoes/clientes/yasmin-masson/'},p.subscription.endpoint);return reply({ok:result.sent>0,...result})}
 return reply({message:'Ação de aviso inválida.'},400);
}
export async function notifyNewBooking(session:string,booking:any){
 try{
 const event=String(booking.id)+':'+booking.created_at;const claimed=await db('lt_yasmin_studio_push_deliveries_internal','?on_conflict=session_id,event_key','POST',{session_id:session,event_key:event,status:'pending'},true);if(!claimed.length)return;
 const date=String(booking.booking_date).split('-').reverse().join('/');const result=await send(session,{title:'Novo agendamento — Yasmin Masson',body:booking.client_name+' · '+booking.service_name+'\n'+date+' às '+booking.start_time.slice(0,5)+' · '+booking.barber_name,tag:'demo-booking-'+event,url:'https://luciaano68-art.github.io/lt-solucoes/clientes/yasmin-masson/'});
 await db('lt_yasmin_studio_push_deliveries_internal','?session_id=eq.'+session+'&event_key=eq.'+encodeURIComponent(event),'PATCH',{status:result.sent?'sent':result.attempted?'failed':'no_subscribers',sent:result.sent,attempted:result.attempted});
 }catch(e){console.error('Falha no aviso exclusivo da estética:',String(e?.message||e))}
}
